// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails agent service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Approve resolves a pending mutating-tool approval or step checkpoint. The
 * delivery and de-registration happen atomically under the lock so a waiter
 * that is simultaneously timing out can't miss a decision: whoever takes the
 * lock first wins — either Approve delivers into the (cap-1, send-once) buffer
 * and removes the entry, or the waiter has already removed it and Approve sees
 * nothing to do. The buffered send never blocks because each channel is sent to
 * at most once before its entry is deleted.
 */
export function Approve(callID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(3194368854, callID, approved);
}

/**
 * AuditLog returns recent agent tool-action records (newest first) — the durable
 * approval/audit surface. A limit <= 0 returns all retained entries.
 */
export function AuditLog(limit: number): $CancellablePromise<$models.AuditEntry[]> {
    return $Call.ByID(1034983590, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Cancel aborts a run.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1456404415, runID);
}

/**
 * ResetConversation clears the backend Agent-mode transcript. Use this when the
 * user clears chat or switches workspaces; provider requests are stateless, but
 * Novera keeps this transcript so follow-up messages behave like one session.
 */
export function ResetConversation(): $CancellablePromise<void> {
    return $Call.ByID(3646622219);
}

/**
 * Start kicks off an agent run for the prompt and returns the run id.
 */
export function Start(prompt: string): $CancellablePromise<string> {
    return $Call.ByID(198483539, prompt);
}

// Private type creation functions
const $$createType0 = $models.AuditEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
