// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CommitResult reports the outcome of a commit and the refreshed status.
 */
export class CommitResult {
    "hash": string;
    "shortHash": string;
    "subject": string;
    "message": string;
    "status": Status;

    /** Creates a new CommitResult instance. */
    constructor($$source: Partial<CommitResult> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new Status());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField4_0($$parsedSource["status"]);
        }
        return new CommitResult($$parsedSource as Partial<CommitResult>);
    }
}

/**
 * DiffContent carries both sides so Monaco's diff editor renders the change.
 */
export class DiffContent {
    "path": string;
    "oldText": string;
    "newText": string;
    "binary": boolean;
    "message": string;

    /** Creates a new DiffContent instance. */
    constructor($$source: Partial<DiffContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("oldText" in $$source)) {
            this["oldText"] = "";
        }
        if (!("newText" in $$source)) {
            this["newText"] = "";
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffContent instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffContent($$parsedSource as Partial<DiffContent>);
    }
}

/**
 * FileChange is one entry in the status lists.
 */
export class FileChange {
    "path": string;
    "oldPath": string;

    /**
     * staged status code
     */
    "index": string;

    /**
     * working-tree status code
     */
    "worktree": string;

    /**
     * modified|added|deleted|untracked|renamed|changed
     */
    "summary": string;
    "staged": boolean;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("oldPath" in $$source)) {
            this["oldPath"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = "";
        }
        if (!("worktree" in $$source)) {
            this["worktree"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("staged" in $$source)) {
            this["staged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

/**
 * Status is the repository snapshot rendered by the Source Control panel.
 */
export class Status {
    /**
     * a repo is present and readable
     */
    "available": boolean;
    "branch": string;
    "head": string;
    "aheadBehind": string;
    "staged": FileChange[];
    "unstaged": FileChange[];
    "message": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }
        if (!("aheadBehind" in $$source)) {
            this["aheadBehind"] = "";
        }
        if (!("staged" in $$source)) {
            this["staged"] = [];
        }
        if (!("unstaged" in $$source)) {
            this["unstaged"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("staged" in $$parsedSource) {
            $$parsedSource["staged"] = $$createField4_0($$parsedSource["staged"]);
        }
        if ("unstaged" in $$parsedSource) {
            $$parsedSource["unstaged"] = $$createField5_0($$parsedSource["unstaged"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = Status.createFrom;
const $$createType1 = FileChange.createFrom;
const $$createType2 = $Create.Array($$createType1);
