// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails git service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Commit commits the staged changes with the given subject/body.
 */
export function Commit(subject: string, body: string): $CancellablePromise<$models.CommitResult> {
    return $Call.ByID(2656160015, subject, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Diff returns the two sides of a change for the Monaco diff editor. When
 * staged is true it shows HEAD vs the index (what `git diff --cached` shows);
 * otherwise it shows the index vs the working tree (what `git diff` shows), so
 * the staged and unstaged rows of one file render their distinct diffs instead
 * of an identical HEAD-vs-worktree view.
 */
export function Diff(rel: string, oldRel: string, staged: boolean): $CancellablePromise<$models.DiffContent> {
    return $Call.ByID(231882249, rel, oldRel, staged).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Stage adds a path to the index.
 */
export function Stage(rel: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(1282875452, rel).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StageAll stages every change (tracked + untracked).
 */
export function StageAll(): $CancellablePromise<$models.Status> {
    return $Call.ByID(749129063).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Status returns the working-tree status, or Available=false with a message
 * when there is no workspace / not a git repo.
 */
export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(644542972).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UnifiedDiff returns a unified `git diff HEAD` for rel (or the whole worktree
 * when rel is empty), capped. Used by the agent's git_diff tool and available
 * to the UI.
 */
export function UnifiedDiff(rel: string): $CancellablePromise<string> {
    return $Call.ByID(1976564439, rel);
}

/**
 * Unstage removes a path from the index (keeps working-tree changes).
 */
export function Unstage(rel: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(4107629929, rel).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CommitResult.createFrom;
const $$createType1 = $models.DiffContent.createFrom;
const $$createType2 = $models.Status.createFrom;
