// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Column is one parsed column of a CREATE TABLE.
 */
export class Column {
    "name": string;

    /**
     * type + modifiers, normalized
     */
    "definition": string;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * ColumnChange describes a column that exists in both tables but differs.
 */
export class ColumnChange {
    "name": string;
    "old": string;
    "new": string;

    /** Creates a new ColumnChange instance. */
    constructor($$source: Partial<ColumnChange> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("old" in $$source)) {
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            this["new"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnChange instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnChange($$parsedSource as Partial<ColumnChange>);
    }
}

/**
 * TableDiff is the per-table column-level diff for a table in both dumps.
 */
export class TableDiff {
    "name": string;
    "addedColumns": Column[];
    "removedColumns": Column[];
    "changedColumns": ColumnChange[];

    /** Creates a new TableDiff instance. */
    constructor($$source: Partial<TableDiff> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("addedColumns" in $$source)) {
            this["addedColumns"] = [];
        }
        if (!("removedColumns" in $$source)) {
            this["removedColumns"] = [];
        }
        if (!("changedColumns" in $$source)) {
            this["changedColumns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDiff {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addedColumns" in $$parsedSource) {
            $$parsedSource["addedColumns"] = $$createField1_0($$parsedSource["addedColumns"]);
        }
        if ("removedColumns" in $$parsedSource) {
            $$parsedSource["removedColumns"] = $$createField2_0($$parsedSource["removedColumns"]);
        }
        if ("changedColumns" in $$parsedSource) {
            $$parsedSource["changedColumns"] = $$createField3_0($$parsedSource["changedColumns"]);
        }
        return new TableDiff($$parsedSource as Partial<TableDiff>);
    }
}

// Private type creation functions
const $$createType0 = Column.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ColumnChange.createFrom;
const $$createType3 = $Create.Array($$createType2);
