// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecretService is the frontend-facing surface of the secret store. It
 * intentionally exposes NO value getter — the UI can store, check, delete, and
 * list credential refs, but can never read a secret back. Only Go services
 * (e.g. llm) read values, via the underlying store.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DeleteKey removes the credential for ref.
 */
export function DeleteKey(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3461365121, ref);
}

/**
 * HasKey reports whether a credential is stored for ref.
 */
export function HasKey(ref: string): $CancellablePromise<boolean> {
    return $Call.ByID(2933307674, ref);
}

/**
 * ListKeys returns the stored refs (never the values).
 */
export function ListKeys(): $CancellablePromise<string[]> {
    return $Call.ByID(3599981601).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetKey stores (encrypted) value under ref.
 */
export function SetKey(ref: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3505611642, ref, value);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
