// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Shell exposes host/OS interactions that require the running application
 * instance (native dialogs, opening external resources). It is intentionally
 * thin — file logic lives in the workspace service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenExternal opens a web/mail URL in the OS default handler. Only http(s) and
 * mailto are allowed; file/UNC and other schemes are rejected so a crafted
 * target can't trigger SMB/NTLM auth or launch arbitrary local handlers.
 */
export function OpenExternal(target: string): $CancellablePromise<void> {
    return $Call.ByID(3864936749, target);
}

/**
 * SaveTextFile opens a native Save dialog seeded with suggestedName and writes
 * content to the chosen path. Returns the path, or "" if the user cancelled.
 */
export function SaveTextFile(suggestedName: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(1367315770, suggestedName, content);
}

/**
 * SelectFolder opens a native directory picker and returns the chosen absolute
 * path. An empty string means the user cancelled.
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1911959446);
}
