// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as datatools$0 from "../datatools/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCsvColumn writes a new CSV/TSV with a constant-valued column appended.
 */
export function AddCsvColumn(rel: string, outRel: string, name: string, value: string): $CancellablePromise<number> {
    return $Call.ByID(993436714, rel, outRel, name, value);
}

/**
 * AnalyzeSQLDump inventories the tables and statements in a .sql/.dump file
 * (streamed; safe on multi-GB dumps). Backs a "Tools" utility and an agent tool.
 */
export function AnalyzeSQLDump(rel: string): $CancellablePromise<datatools$0.DumpSummary> {
    return $Call.ByID(2179841155, rel).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Close clears the active workspace.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1404506799);
}

/**
 * ConvertCsvToSql streams a CSV/TSV into a SQL file (CREATE TABLE + INSERTs) at a
 * workspace-relative output path.
 */
export function ConvertCsvToSql(rel: string, outRel: string, tableName: string, includeCreate: boolean): $CancellablePromise<datatools$0.SQLConvertSummary> {
    return $Call.ByID(2055226463, rel, outRel, tableName, includeCreate).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateDir creates a directory (and any missing parents).
 */
export function CreateDir(rel: string): $CancellablePromise<$models.Entry> {
    return $Call.ByID(75400064, rel).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CreateFile creates an empty file (error if it already exists).
 */
export function CreateFile(rel: string): $CancellablePromise<$models.Entry> {
    return $Call.ByID(4184311319, rel).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Current returns info about the open workspace.
 */
export function Current(): $CancellablePromise<$models.Info> {
    return $Call.ByID(2227016158).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Delete removes a file or directory (recursively) within the workspace.
 */
export function Delete(rel: string): $CancellablePromise<void> {
    return $Call.ByID(2068037430, rel);
}

/**
 * Diagnostics scans workspace text files for TODO/FIXME/HACK/XXX markers and
 * merge-conflict markers. Deterministic, bounded, no compiler/network.
 */
export function Diagnostics(): $CancellablePromise<$models.DiagnosticsResult> {
    return $Call.ByID(3498416339).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DumpTableToCsv extracts a table's pg_dump COPY block into a CSV file at outRel.
 */
export function DumpTableToCsv(rel: string, table: string, outRel: string): $CancellablePromise<number> {
    return $Call.ByID(2542638164, rel, table, outRel);
}

/**
 * ExtractDumpTable copies one table's statements out of a SQL dump into outRel.
 */
export function ExtractDumpTable(rel: string, table: string, outRel: string): $CancellablePromise<$models.DumpExtractResult> {
    return $Call.ByID(3197802308, rel, table, outRel).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * InferTableSchema infers a SQL-ish column schema for a CSV/TSV file from a
 * bounded sample (column types, null counts, examples). A "Tools" utility and an
 * agent tool both call this. delimiter "" auto-detects.
 */
export function InferTableSchema(rel: string, delimiter: string): $CancellablePromise<datatools$0.SchemaResult> {
    return $Call.ByID(3762455854, rel, delimiter).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListAllFiles returns slash-relative paths of every file under the workspace
 * (skipping heavy/build directories), capped. Powers quick-open and search.
 */
export function ListAllFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(3475303835).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListDir returns the immediate children of rel ("" or "." for the root),
 * directories first then files, each sorted case-insensitively.
 */
export function ListDir(rel: string): $CancellablePromise<$models.Entry[]> {
    return $Call.ByID(2938491772, rel).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Open sets the active workspace to dir after validating it is a directory.
 */
export function Open(dir: string): $CancellablePromise<$models.Info> {
    return $Call.ByID(469184077, dir).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PreviewCsvToSql returns the SQL (CREATE TABLE + INSERTs) for the first rows of
 * a CSV/TSV file — a glance before writing the full output.
 */
export function PreviewCsvToSql(rel: string, tableName: string, includeCreate: boolean): $CancellablePromise<string> {
    return $Call.ByID(868013008, rel, tableName, includeCreate);
}

/**
 * ProjectCsv writes a new CSV/TSV keeping only the named columns, in order.
 */
export function ProjectCsv(rel: string, outRel: string, columns: string[]): $CancellablePromise<number> {
    return $Call.ByID(4211943386, rel, outRel, columns);
}

/**
 * QueryTable returns a window of a CSV/TSV/XLSX file for the analytics grid. The
 * first row is the header. Browsing reads only the requested window straight off
 * disk; a filter or sort is applied across the entire file (the realised result
 * is cached so paging through it doesn't rescan).
 */
export function QueryTable(rel: string, q: $models.TableQuery): $CancellablePromise<$models.TablePage> {
    return $Call.ByID(3760756937, rel, q).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ReadFile returns file content for the editor. Binary or oversized files are
 * flagged and returned with empty content so the UI can render a placeholder.
 */
export function ReadFile(rel: string): $CancellablePromise<$models.FileContent> {
    return $Call.ByID(3060087111, rel).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ReadFileRange returns one bounded, encoding-aware byte-range page using
 * ReadAt, so a multi-GB file can be inspected without loading it whole. Source
 * encoding is detected from the head; text boundaries are decoder-aligned and
 * binary files retain exact requested offsets as a hex dump.
 */
export function ReadFileRange(rel: string, offset: number, length: number): $CancellablePromise<$models.FileChunk> {
    return $Call.ByID(3731277180, rel, offset, length).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Rename moves fromRel to toRel within the workspace.
 */
export function Rename(fromRel: string, toRel: string): $CancellablePromise<void> {
    return $Call.ByID(3533008927, fromRel, toRel);
}

/**
 * Root returns the current absolute workspace root (empty if none open). It is
 * also shared with sibling services (e.g. git) that operate on the same root.
 */
export function Root(): $CancellablePromise<string> {
    return $Call.ByID(3841346601);
}

/**
 * Search does a literal substring search across workspace files (skipping
 * heavy/build dirs, binaries, and oversized files), returning capped matches.
 */
export function Search(query: string, caseSensitive: boolean): $CancellablePromise<$models.SearchResult> {
    return $Call.ByID(1503656989, query, caseSensitive).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SplitDump writes each table in a SQL dump to outDirRel/<table>.sql.
 */
export function SplitDump(rel: string, outDirRel: string): $CancellablePromise<$models.DumpExtractResult> {
    return $Call.ByID(1256656129, rel, outDirRel).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * TableInfo counts the data rows of a tabular file and (for CSV/TSV) builds a
 * sparse row->byte-offset index, cached per file+delimiter. It's meant to be
 * called in the background after a file opens: browsing works immediately and
 * the true total / fast jumps light up once this returns.
 */
export function TableInfo(rel: string, delimiter: string): $CancellablePromise<$models.TableInfoResult> {
    return $Call.ByID(2147294175, rel, delimiter).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * TransformDump streams a SQL dump through cleanup presets (remove DEFINER,
 * rewrite ENGINE/CHARSET, drop AUTO_INCREMENT, rename a database) into outRel.
 */
export function TransformDump(rel: string, outRel: string, t: datatools$0.DumpTransform): $CancellablePromise<datatools$0.DumpTransformSummary> {
    return $Call.ByID(3289929665, rel, outRel, t).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * WriteFile writes content atomically. If the file already exists and
 * expectedRevision is non-empty, the on-disk revision must match or ErrStale is
 * returned (optimistic concurrency). content is UTF-8; encoding (utf-8,
 * utf-8-bom, utf-16le, utf-16be, latin-1; empty = utf-8) selects the on-disk
 * encoding so a non-UTF-8 file round-trips. Returns the new revision.
 */
export function WriteFile(rel: string, content: string, expectedRevision: string, encoding: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3558372542, rel, content, expectedRevision, encoding).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = datatools$0.DumpSummary.createFrom;
const $$createType1 = datatools$0.SQLConvertSummary.createFrom;
const $$createType2 = $models.Entry.createFrom;
const $$createType3 = $models.Info.createFrom;
const $$createType4 = $models.DiagnosticsResult.createFrom;
const $$createType5 = $models.DumpExtractResult.createFrom;
const $$createType6 = datatools$0.SchemaResult.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Array($$createType2);
const $$createType9 = $models.TablePage.createFrom;
const $$createType10 = $models.FileContent.createFrom;
const $$createType11 = $models.FileChunk.createFrom;
const $$createType12 = $models.SearchResult.createFrom;
const $$createType13 = $models.TableInfoResult.createFrom;
const $$createType14 = datatools$0.DumpTransformSummary.createFrom;
const $$createType15 = $models.WriteResult.createFrom;
