// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails LLM service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops an in-flight request.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(706103017, id);
}

/**
 * ListModels asks the configured provider for its available models (powers the
 * model picker; also a connectivity check).
 */
export function ListModels(): $CancellablePromise<string[]> {
    return $Call.ByID(3362258213).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Send starts a streaming completion and returns a request id. Tokens arrive on
 * the "llm:delta" event; completion on "llm:done"; failures on "llm:error".
 */
export function Send(req: $models.SendRequest): $CancellablePromise<string> {
    return $Call.ByID(2338701865, req);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
