// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails service for settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteLLMAPIKey detaches then removes only the current provider-owned key.
 */
export function DeleteLLMAPIKey(): $CancellablePromise<void> {
    return $Call.ByID(3613693460);
}

/**
 * GetLLMAPIKeyStatus reports whether the current credential is verified,
 * quarantined legacy evidence, absent, or temporarily unverifiable.
 */
export function GetLLMAPIKeyStatus(): $CancellablePromise<$models.LLMAPIKeyStatus> {
    return $Call.ByID(2395146497).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HasLLMAPIKey is retained for compatibility and reports true only for a
 * backend-verified current origin-bound key.
 */
export function HasLLMAPIKey(): $CancellablePromise<boolean> {
    return $Call.ByID(197256875);
}

/**
 * Load returns the persisted settings, falling back to defaults for any missing
 * fields or if no file exists yet. Legacy credentials remain quarantined; the
 * only legacy metadata repair recognizes an already-completed explicit
 * replacement whose settings-file publication was interrupted.
 */
export function Load(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2509701163).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LoadError returns the latched, actionable persistence diagnostic, if any.
 * Load itself remains a best-effort read for startup compatibility, while this
 * separate bound method lets the renderer distinguish defaults from a corrupt
 * or unsafe primary file.
 */
export function LoadError(): $CancellablePromise<string> {
    return $Call.ByID(4200777811);
}

/**
 * RememberWorkspace records path as the last-opened workspace and pushes it to
 * the front of the recents list, returning the updated settings.
 */
export function RememberWorkspace(path: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2975979585, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save persists the full settings object atomically.
 */
export function Save($in: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2754879942, $in);
}

/**
 * SetLLMAPIKey stores an API key under the backend-owned ref for the currently
 * persisted provider/origin and attaches that ref to settings. The renderer
 * supplies only the new value; it cannot select or reattach an existing ref.
 */
export function SetLLMAPIKey(value: string): $CancellablePromise<void> {
    return $Call.ByID(1125480403, value);
}

// Private type creation functions
const $$createType0 = $models.LLMAPIKeyStatus.createFrom;
const $$createType1 = $models.Settings.createFrom;
