// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AuditEntry is one recorded agent tool action. The log is the durable,
 * after-the-fact record of what the agent did and which mutations the user
 * approved or denied — the approval/audit surface the UI reads back.
 */
export class AuditEntry {
    "formatVersion"?: number;

    /**
     * RFC3339
     */
    "time": string;
    "runId": string;
    "callId": string;
    "tool": string;

    /**
     * bounded target/size metadata; never raw free-form payloads
     */
    "summary": string;

    /**
     * auto | approved | denied
     */
    "decision": string;

    /**
     * ok | error | denied
     */
    "status": string;

    /**
     * bounded outcome metadata; never raw result/error text
     */
    "detail": string;

    /**
     * exact reviewed operation, blank for automatic actions
     */
    "intentDigest"?: string;

    /** Creates a new AuditEntry instance. */
    constructor($$source: Partial<AuditEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("callId" in $$source)) {
            this["callId"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEntry($$parsedSource as Partial<AuditEntry>);
    }
}
