// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails agent service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortWorkspaceTransition reattaches the pre-transition transcript when the
 * old workspace remained (or was restored). Like End, the opaque token makes a
 * stale renderer continuation harmless.
 */
export function AbortWorkspaceTransition(token: string): $CancellablePromise<void> {
    return $Call.ByID(997124165, token);
}

/**
 * Approve resolves only a non-operation continuation checkpoint. Sensitive
 * tool operations use ApproveIntent so the decision is bound to exact bytes.
 */
export function Approve(callID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(3194368854, callID, approved);
}

/**
 * ApproveIntent resolves a pending sensitive operation only when the renderer
 * returns the digest of the exact canonical intent it displayed. Delivery,
 * expiry checking, and removal are atomic, so a decision is one-use.
 */
export function ApproveIntent(callID: string, digest: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(1546732532, callID, digest, approved);
}

/**
 * AuditLog returns recent agent tool-action records (newest first) — the durable
 * approval/audit surface. A limit <= 0 returns all retained entries.
 */
export function AuditLog(limit: number): $CancellablePromise<$models.AuditEntry[]> {
    return $Call.ByID(1034983590, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BeginWorkspaceTransition closes Agent admission before canceling and waiting
 * for old-workspace work. The returned opaque token must be passed to
 * EndWorkspaceTransition only after Workspace.Open/Close (including any
 * rollback) has settled. A newer Begin supersedes older tokens, so a stale
 * renderer continuation cannot reopen admission during a newer transition.
 */
export function BeginWorkspaceTransition(): $CancellablePromise<string> {
    return $Call.ByID(91515732);
}

/**
 * Cancel signals a run to stop. The run finalizer retains and releases the
 * active-run lease only after in-flight work has actually returned.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1456404415, runID);
}

/**
 * EndWorkspaceTransition reopens Agent admission for the current transition.
 * Stale or duplicate tokens are intentionally ignored.
 */
export function EndWorkspaceTransition(token: string): $CancellablePromise<void> {
    return $Call.ByID(3719486856, token);
}

/**
 * ResetConversation cancels and awaits the active run before clearing the
 * backend transcript. Workspace transitions must propagate a returned timeout:
 * proceeding while a context-free legacy tool is still running would let work
 * from the old workspace cross into the new one.
 */
export function ResetConversation(): $CancellablePromise<void> {
    return $Call.ByID(3646622219);
}

/**
 * Start kicks off an agent run for the prompt and returns the run id.
 */
export function Start(prompt: string): $CancellablePromise<string> {
    return $Call.ByID(198483539, prompt);
}

// Private type creation functions
const $$createType0 = $models.AuditEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
