// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes streaming, windowed access to very large files. It is
 * bound to the frontend by Wails; the whole-file content never crosses the
 * bridge — only bounded, line-aligned windows do.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob cancels the active long transform, if any. The transform aborts and
 * removes its partial output.
 */
export function CancelJob(): $CancellablePromise<void> {
    return $Call.ByID(2867360005);
}

/**
 * CloseFile releases a file's resources.
 */
export function CloseFile(fileID: string): $CancellablePromise<void> {
    return $Call.ByID(1864103002, fileID);
}

/**
 * CsvAddColumnViaDialog writes a new CSV with a constant column appended to every
 * row (including the header, which becomes the value).
 */
export function CsvAddColumnViaDialog(fileID: string, delimiter: string, columnCount: number, value: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1110146483, fileID, delimiter, columnCount, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvDedupeViaDialog writes a new CSV dropping duplicate rows — by a key column
 * (keyColumn>=0) or the whole row (keyColumn<0). First occurrence wins.
 */
export function CsvDedupeViaDialog(fileID: string, delimiter: string, hasHeader: boolean, keyColumn: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1348673393, fileID, delimiter, hasHeader, keyColumn).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportJSONLViaDialog streams the CSV to newline-delimited JSON.
 */
export function CsvExportJSONLViaDialog(fileID: string, delimiter: string, hasHeader: boolean, numberKeys: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(724714548, fileID, delimiter, hasHeader, numberKeys).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportSQLiteViaDialog streams the CSV into a new SQLite .db file.
 */
export function CsvExportSQLiteViaDialog(fileID: string, delimiter: string, hasHeader: boolean, tableName: string, typedCells: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1436630870, fileID, delimiter, hasHeader, tableName, typedCells).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportXLSXViaDialog streams the CSV into a new .xlsx workbook.
 */
export function CsvExportXLSXViaDialog(fileID: string, delimiter: string, hasHeader: boolean, sheetName: string, typedCells: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2750541179, fileID, delimiter, hasHeader, sheetName, typedCells).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvFilterViaDialog writes a new CSV keeping only rows where the chosen column
 * matches op/value (eq, ne, contains, gt, lt, empty, nonempty). Source untouched.
 */
export function CsvFilterViaDialog(fileID: string, delimiter: string, hasHeader: boolean, column: number, op: string, value: string, negate: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2426919946, fileID, delimiter, hasHeader, column, op, value, negate).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvInspect detects the most likely delimiter (and ranked alternatives) from a
 * bounded sample, so the UI can preselect it and offer overrides.
 */
export function CsvInspect(fileID: string): $CancellablePromise<$models.CsvInspectResult> {
    return $Call.ByID(792128788, fileID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CsvMarkdownPreview returns the current preview as a Markdown table (for copy).
 */
export function CsvMarkdownPreview(fileID: string, delimiter: string, hasHeader: boolean, maxRows: number): $CancellablePromise<string> {
    return $Call.ByID(403569035, fileID, delimiter, hasHeader, maxRows);
}

export function CsvPreview(fileID: string, delimiter: string, hasHeader: boolean, maxRows: number): $CancellablePromise<$models.CsvPreviewResult> {
    return $Call.ByID(1308065476, fileID, delimiter, hasHeader, maxRows).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CsvProfile profiles each column (null %, distinct, min/max, top values) and
 * counts ragged rows over a bounded sample.
 */
export function CsvProfile(fileID: string, delimiter: string, hasHeader: boolean): $CancellablePromise<$models.CsvProfileResult> {
    return $Call.ByID(3488062821, fileID, delimiter, hasHeader).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CsvProjectViaDialog writes a new CSV keeping only keepIndices (0-based) in the
 * given order — used for drop-column and reorder.
 */
export function CsvProjectViaDialog(fileID: string, delimiter: string, keepIndices: number[]): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(165873055, fileID, delimiter, keepIndices).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvRedactViaDialog writes an anonymized copy of the CSV with the chosen columns
 * masked, for sharing a dataset without leaking PII. Source is never modified.
 */
export function CsvRedactViaDialog(fileID: string, delimiter: string, hasHeader: boolean, columns: $models.CsvRedactColumn[], replacement: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3188274975, fileID, delimiter, hasHeader, columns, replacement).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvSampleViaDialog writes a new CSV keeping every Nth data row (header kept),
 * for shrinking a huge dump to a representative slice.
 */
export function CsvSampleViaDialog(fileID: string, delimiter: string, hasHeader: boolean, everyN: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3744408314, fileID, delimiter, hasHeader, everyN).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CsvSchema(fileID: string, delimiter: string, hasHeader: boolean): $CancellablePromise<$models.CsvSchemaResult> {
    return $Call.ByID(3148189243, fileID, delimiter, hasHeader).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CsvToSQLConfigPreview returns a short sample of the SQL for a full config.
 */
export function CsvToSQLConfigPreview(fileID: string, cfg: $models.CsvSqlConfig): $CancellablePromise<string> {
    return $Call.ByID(710905099, fileID, cfg);
}

/**
 * CsvToSQLConfigViaDialog streams the whole CSV to a .sql file using a full
 * column-mapping config (select/rename/type, insert mode, batch, null, policy).
 */
export function CsvToSQLConfigViaDialog(fileID: string, cfg: $models.CsvSqlConfig): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3756880875, fileID, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvToSQLPreview returns a short sample of the generated SQL.
 */
export function CsvToSQLPreview(fileID: string, delimiter: string, tableName: string, hasHeader: boolean, includeCreate: boolean): $CancellablePromise<string> {
    return $Call.ByID(3439646149, fileID, delimiter, tableName, hasHeader, includeCreate);
}

/**
 * CsvToSQLViaDialog streams the whole CSV to a .sql file of INSERTs.
 */
export function CsvToSQLViaDialog(fileID: string, delimiter: string, tableName: string, hasHeader: boolean, includeCreate: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(428322317, fileID, delimiter, tableName, hasHeader, includeCreate).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiscardEdits drops all staged edits.
 */
export function DiscardEdits(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(3793258711, fileID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * FileSize re-stats the file on disk and returns its current size. Cheap — used
 * to poll a growing file (tail/follow) without reopening it.
 */
export function FileSize(fileID: string): $CancellablePromise<number> {
    return $Call.ByID(1707831887, fileID);
}

/**
 * FindNext finds the first match at/after fromByte (single streaming pass).
 */
export function FindNext(fileID: string, query: string, fromByte: number, regex: boolean, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchHit> {
    return $Call.ByID(814300810, fileID, query, fromByte, regex, caseSensitive, wholeWord).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * FindPrev finds the first match before beforeByte (streaming backward pass).
 */
export function FindPrev(fileID: string, query: string, beforeByte: number, regex: boolean, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchHit> {
    return $Call.ByID(1897676702, fileID, query, beforeByte, regex, caseSensitive, wholeWord).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCsvGrid parses a bounded, line-aligned byte window into CSV rows for the
 * grid view. Rows are returned as data (no header special-casing); the frontend
 * supplies column labels from the schema. Scrolling loads adjacent windows.
 */
export function GetCsvGrid(fileID: string, delimiter: string, startByte: number, maxBytes: number): $CancellablePromise<$models.CsvGridResult> {
    return $Call.ByID(885416396, fileID, delimiter, startByte, maxBytes).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetDiffWindow returns the edited and original text for a line-aligned window,
 * for the side-by-side diff view.
 */
export function GetDiffWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.DiffWindow> {
    return $Call.ByID(2293174843, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetEditWindow returns a byte-exact, line-aligned UTF-8 window that reflects
 * staged edits (reads the edited view when edits exist, else the raw document).
 * startByte is aligned down to a line start; pass any byte for go-to / prev.
 */
export function GetEditWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(2343628796, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetHexWindow returns a bounded hex dump of the file starting at (16-byte
 * aligned) startByte. Scrolling loads adjacent windows; the file is never fully
 * read. Works for any file, including binary.
 */
export function GetHexWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.HexWindow> {
    return $Call.ByID(914678545, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetNextWindow continues forward from a previous window's NextByte.
 */
export function GetNextWindow(fileID: string, fromByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(3363176709, fileID, fromByte, maxBytes).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPrevWindow returns the window immediately preceding currentStart, aligned
 * to a line boundary so it reads cleanly.
 */
export function GetPrevWindow(fileID: string, currentStart: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(1960744817, fileID, currentStart, maxBytes).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetStagedEdits returns the pending edits (source-anchored) for the diff panel.
 */
export function GetStagedEdits(fileID: string): $CancellablePromise<$models.StagedEdit[]> {
    return $Call.ByID(1432012583, fileID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetStagingState reports current pending-edit status.
 */
export function GetStagingState(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(2175041062, fileID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetWindow returns a window beginning at startByte (clamped, aligned by the
 * document's own line handling).
 */
export function GetWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(2814923928, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * HarvestMatchesViaDialog runs a regex over the whole file and writes every
 * match, one per line, to a chosen file — e.g. extract every email or id.
 */
export function HarvestMatchesViaDialog(fileID: string, pattern: string, caseInsensitive: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(4019629850, fileID, pattern, caseInsensitive).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenFile opens path, starts background indexing, and returns its metadata.
 */
export function OpenFile(path: string): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(382069238, path).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * OpenViaDialog shows a native open-file dialog and opens the chosen file. A
 * cancelled dialog returns an empty FileMeta (FileID == "") with a nil error.
 */
export function OpenViaDialog(): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(2517771520).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * RefreshFile reloads the file from disk under the same id (fresh size + line
 * index), for following a growing file or picking up external changes. Any
 * staged edits are discarded, so callers should confirm before using it on a
 * file with pending edits.
 */
export function RefreshFile(fileID: string): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(1000304125, fileID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ResolveLine maps a 1-based line number to a byte offset (exact if the index
 * is built, otherwise approximate). Returns 0 when the line can't be resolved.
 */
export function ResolveLine(fileID: string, line: number): $CancellablePromise<number> {
    return $Call.ByID(4183015142, fileID, line);
}

/**
 * SaveCopy writes the edited file to dstPath via the streaming copy-through
 * pipeline (source untouched; staged edits remain).
 */
export function SaveCopy(fileID: string, dstPath: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(3494652756, fileID, dstPath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SaveCopyViaDialog shows a native save dialog and writes the edited copy there.
 * A cancelled dialog returns an empty SaveResult (Mode == "") with nil error.
 */
export function SaveCopyViaDialog(fileID: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1169867108, fileID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SavePatch applies the staged edits in place (length-preserving only) with a
 * crash-safe reverse-patch sidecar, then refreshes the document from disk.
 */
export function SavePatch(fileID: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1419832985, fileID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SearchAll collects up to maxHits matches across the whole file with previews,
 * for a results panel. The query is encoded into the file's encoding first.
 */
export function SearchAll(fileID: string, query: string, regex: boolean, caseSensitive: boolean, wholeWord: boolean, maxHits: number): $CancellablePromise<$models.SearchAllResult> {
    return $Call.ByID(1598277695, fileID, query, regex, caseSensitive, wholeWord, maxHits).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SqlAnalyze streams a single pass over the dump to discover tables and stats,
 * caching the result for later extraction. This is a full pass — the UI should
 * show progress for huge files.
 */
export function SqlAnalyze(fileID: string): $CancellablePromise<$models.SqlSummaryResult> {
    return $Call.ByID(1563764376, fileID).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * SqlApplyPresetViaDialog runs a named cleanup preset, streaming the result to a
 * chosen file. Presets that need arguments (e.g. change-database) take them via
 * a1..a4; the source is never modified.
 */
export function SqlApplyPresetViaDialog(fileID: string, name: string, a1: string, a2: string, a3: string, a4: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1655907585, fileID, name, a1, a2, a3, a4).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractDataViaDialog writes just the INSERT rows for a table (no DDL).
 */
export function SqlExtractDataViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2269513535, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractSchemaViaDialog writes just the DDL (CREATE TABLE / structure) with
 * no INSERT data. An empty tableName extracts the whole dump's schema.
 */
export function SqlExtractSchemaViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1617829806, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractTableViaDialog writes one table's byte range to a chosen output
 * file (streamed; never materializes the whole dump).
 */
export function SqlExtractTableViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3125375737, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlLint reports dump issues from the cached analysis: empty tables, DEFINER
 * usage, mixed charsets/collations, and the largest tables. No new file scan.
 */
export function SqlLint(fileID: string): $CancellablePromise<$models.SqlLintResult> {
    return $Call.ByID(3422427641, fileID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SqlListPresets returns the available SQL cleanup preset names.
 */
export function SqlListPresets(): $CancellablePromise<string[]> {
    return $Call.ByID(69917632).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * SqlReplaceViaDialog streams a find/replace (plain or regex) to a new file —
 * also used for table-prefix renames. The source is never modified.
 */
export function SqlReplaceViaDialog(fileID: string, find: string, replaceWith: string, regex: boolean, caseInsensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1077960636, fileID, find, replaceWith, regex, caseInsensitive, wholeWord).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlReshapeInsertsViaDialog rewrites INSERT row layout, streaming to a new file.
 * mode "single" explodes extended INSERTs into one row each (good for line diffs);
 * mode "multi" batches consecutive single-row INSERTs (good for fast re-import).
 */
export function SqlReshapeInsertsViaDialog(fileID: string, mode: string, batchSize: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3588725676, fileID, mode, batchSize).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlSampleFixtureViaDialog writes a small "dev fixture" dump: each table's DDL
 * plus only its first rowsPerTable INSERT rows. Turns a prod dump into a tiny,
 * shareable seed without ever materialising the whole file.
 */
export function SqlSampleFixtureViaDialog(fileID: string, rowsPerTable: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3698625949, fileID, rowsPerTable).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlSchemaDiff compares the table/column structure of two analyzed dumps
 * (A = baseline, B = new). Both must be analyzed first.
 */
export function SqlSchemaDiff(fileIDA: string, fileIDB: string): $CancellablePromise<$models.SqlSchemaDiffResult> {
    return $Call.ByID(3883908852, fileIDA, fileIDB).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SqlSplitByTableViaDialog writes one .sql file per table into a chosen folder.
 */
export function SqlSplitByTableViaDialog(fileID: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3832893453, fileID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StageEdit reconciles the window [startByte, startByte+origLen) with newText.
 * It trims the common prefix/suffix so only the genuinely changed bytes are
 * staged — keeping the diff granular and in-place patches minimal.
 */
export function StageEdit(fileID: string, startByte: number, origLen: number, newText: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(756414490, fileID, startByte, origLen, newText).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TransformResult.createFrom;
const $$createType1 = $models.CsvInspectResult.createFrom;
const $$createType2 = $models.CsvPreviewResult.createFrom;
const $$createType3 = $models.CsvProfileResult.createFrom;
const $$createType4 = $models.CsvSchemaResult.createFrom;
const $$createType5 = $models.StagingState.createFrom;
const $$createType6 = $models.SearchHit.createFrom;
const $$createType7 = $models.CsvGridResult.createFrom;
const $$createType8 = $models.DiffWindow.createFrom;
const $$createType9 = $models.Window.createFrom;
const $$createType10 = $models.HexWindow.createFrom;
const $$createType11 = $models.StagedEdit.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.FileMeta.createFrom;
const $$createType14 = $models.SaveResult.createFrom;
const $$createType15 = $models.SearchAllResult.createFrom;
const $$createType16 = $models.SqlSummaryResult.createFrom;
const $$createType17 = $models.SqlLintResult.createFrom;
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = $models.SqlSchemaDiffResult.createFrom;
