// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as csv$0 from "./plugins/csv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemadiff$0 from "./plugins/sql/schemadiff/models.js";

export class CsvColumn {
    "name": string;
    "sqlType": string;
    "nonNull": number;
    "null": number;
    "samples": string[];

    /** Creates a new CsvColumn instance. */
    constructor($$source: Partial<CsvColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sqlType" in $$source)) {
            this["sqlType"] = "";
        }
        if (!("nonNull" in $$source)) {
            this["nonNull"] = 0;
        }
        if (!("null" in $$source)) {
            this["null"] = 0;
        }
        if (!("samples" in $$source)) {
            this["samples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvColumn {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField4_0($$parsedSource["samples"]);
        }
        return new CsvColumn($$parsedSource as Partial<CsvColumn>);
    }
}

export class CsvDelimiterOption {
    "delimiter": string;
    "name": string;
    "columns": number;
    "score": number;

    /** Creates a new CsvDelimiterOption instance. */
    constructor($$source: Partial<CsvDelimiterOption> = {}) {
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvDelimiterOption instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvDelimiterOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvDelimiterOption($$parsedSource as Partial<CsvDelimiterOption>);
    }
}

export class CsvGridResult {
    "fileId": string;
    "generation": number;
    "encoding": string;
    "startByte": number;
    "nextByte": number;

    /**
     * approximate physical line of the first record
     */
    "startRow": number;
    "rows": string[][];
    "columns": number;
    "sourceBytes": number;
    "decodedBytes": number;
    "atBof": boolean;
    "atEof": boolean;

    /** Creates a new CsvGridResult instance. */
    constructor($$source: Partial<CsvGridResult> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("startByte" in $$source)) {
            this["startByte"] = 0;
        }
        if (!("nextByte" in $$source)) {
            this["nextByte"] = 0;
        }
        if (!("startRow" in $$source)) {
            this["startRow"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("columns" in $$source)) {
            this["columns"] = 0;
        }
        if (!("sourceBytes" in $$source)) {
            this["sourceBytes"] = 0;
        }
        if (!("decodedBytes" in $$source)) {
            this["decodedBytes"] = 0;
        }
        if (!("atBof" in $$source)) {
            this["atBof"] = false;
        }
        if (!("atEof" in $$source)) {
            this["atEof"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvGridResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvGridResult {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField6_0($$parsedSource["rows"]);
        }
        return new CsvGridResult($$parsedSource as Partial<CsvGridResult>);
    }
}

export class CsvInspectResult {
    "generation": number;
    "delimiter": string;
    "delimiterName": string;
    "confidence": string;
    "columns": number;
    "hasHeader": boolean;
    "candidates": CsvDelimiterOption[];
    "warnings": string[];

    /** Creates a new CsvInspectResult instance. */
    constructor($$source: Partial<CsvInspectResult> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }
        if (!("delimiterName" in $$source)) {
            this["delimiterName"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = 0;
        }
        if (!("hasHeader" in $$source)) {
            this["hasHeader"] = false;
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvInspectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvInspectResult {
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField6_0($$parsedSource["candidates"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new CsvInspectResult($$parsedSource as Partial<CsvInspectResult>);
    }
}

export class CsvPreviewResult {
    "generation": number;
    "header": string[];
    "rows": string[][];
    "warnings": string[];

    /** Creates a new CsvPreviewResult instance. */
    constructor($$source: Partial<CsvPreviewResult> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("header" in $$source)) {
            this["header"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvPreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvPreviewResult {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("header" in $$parsedSource) {
            $$parsedSource["header"] = $$createField1_0($$parsedSource["header"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new CsvPreviewResult($$parsedSource as Partial<CsvPreviewResult>);
    }
}

/**
 * CsvProfileResult is a per-column data profile over a bounded sample.
 */
export class CsvProfileResult {
    "generation": number;
    "columns": csv$0.ColumnProfile[];
    "recordsScanned": number;
    "raggedRows": number;
    "truncated": boolean;

    /** Creates a new CsvProfileResult instance. */
    constructor($$source: Partial<CsvProfileResult> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("recordsScanned" in $$source)) {
            this["recordsScanned"] = 0;
        }
        if (!("raggedRows" in $$source)) {
            this["raggedRows"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvProfileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvProfileResult {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new CsvProfileResult($$parsedSource as Partial<CsvProfileResult>);
    }
}

/**
 * CsvRedactColumn is one column to mask in a redaction.
 */
export class CsvRedactColumn {
    "index": number;

    /**
     * null | fixed | hash | email
     */
    "mode": string;

    /** Creates a new CsvRedactColumn instance. */
    constructor($$source: Partial<CsvRedactColumn> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvRedactColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvRedactColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvRedactColumn($$parsedSource as Partial<CsvRedactColumn>);
    }
}

export class CsvSchemaResult {
    "generation": number;
    "columns": CsvColumn[];
    "hasHeader": boolean;
    "warnings": string[];

    /** Creates a new CsvSchemaResult instance. */
    constructor($$source: Partial<CsvSchemaResult> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("hasHeader" in $$source)) {
            this["hasHeader"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvSchemaResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvSchemaResult {
        const $$createField1_0 = $$createType7;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new CsvSchemaResult($$parsedSource as Partial<CsvSchemaResult>);
    }
}

/**
 * CsvSqlColumnConfig describes one output column of a CSV→SQL conversion.
 */
export class CsvSqlColumnConfig {
    /**
     * 0-based source field index
     */
    "source": number;

    /**
     * output column name
     */
    "name": string;

    /**
     * SQL type; BOOLEAN also controls value validation/emission
     */
    "type": string;

    /**
     * whether to emit this column
     */
    "include": boolean;

    /** Creates a new CsvSqlColumnConfig instance. */
    constructor($$source: Partial<CsvSqlColumnConfig> = {}) {
        if (!("source" in $$source)) {
            this["source"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("include" in $$source)) {
            this["include"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvSqlColumnConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvSqlColumnConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvSqlColumnConfig($$parsedSource as Partial<CsvSqlColumnConfig>);
    }
}

/**
 * CsvSqlConfig is the full, flexible CSV→SQL conversion request.
 */
export class CsvSqlConfig {
    "delimiter": string;
    "hasHeader": boolean;
    "tableName": string;
    "columns": CsvSqlColumnConfig[];
    "includeCreate": boolean;

    /**
     * insert | ignore | replace
     */
    "insertMode": string;
    "batchSize": number;
    "nullValues": string[];

    /**
     * fail | skip-row | replace
     */
    "onInvalid": string;

    /** Creates a new CsvSqlConfig instance. */
    constructor($$source: Partial<CsvSqlConfig> = {}) {
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }
        if (!("hasHeader" in $$source)) {
            this["hasHeader"] = false;
        }
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("includeCreate" in $$source)) {
            this["includeCreate"] = false;
        }
        if (!("insertMode" in $$source)) {
            this["insertMode"] = "";
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }
        if (!("nullValues" in $$source)) {
            this["nullValues"] = [];
        }
        if (!("onInvalid" in $$source)) {
            this["onInvalid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvSqlConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvSqlConfig {
        const $$createField3_0 = $$createType9;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("nullValues" in $$parsedSource) {
            $$parsedSource["nullValues"] = $$createField7_0($$parsedSource["nullValues"]);
        }
        return new CsvSqlConfig($$parsedSource as Partial<CsvSqlConfig>);
    }
}

/**
 * CsvTextPreviewResult binds rendered preview text to the exact open session
 * generation that supplied its bytes. Callers must echo that generation in a
 * later artifact request.
 */
export class CsvTextPreviewResult {
    "generation": number;
    "text": string;

    /** Creates a new CsvTextPreviewResult instance. */
    constructor($$source: Partial<CsvTextPreviewResult> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvTextPreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvTextPreviewResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvTextPreviewResult($$parsedSource as Partial<CsvTextPreviewResult>);
    }
}

/**
 * DiffWindow holds corresponding original and edited spans. StartByte and
 * NextByte remain edited-coordinate aliases for bridge compatibility.
 */
export class DiffWindow {
    "startByte": number;
    "nextByte": number;
    "editedStartByte": number;
    "editedNextByte": number;
    "originalStartByte": number;
    "originalNextByte": number;
    "original": string;
    "edited": string;
    "atBof": boolean;
    "atEof": boolean;

    /** Creates a new DiffWindow instance. */
    constructor($$source: Partial<DiffWindow> = {}) {
        if (!("startByte" in $$source)) {
            this["startByte"] = 0;
        }
        if (!("nextByte" in $$source)) {
            this["nextByte"] = 0;
        }
        if (!("editedStartByte" in $$source)) {
            this["editedStartByte"] = 0;
        }
        if (!("editedNextByte" in $$source)) {
            this["editedNextByte"] = 0;
        }
        if (!("originalStartByte" in $$source)) {
            this["originalStartByte"] = 0;
        }
        if (!("originalNextByte" in $$source)) {
            this["originalNextByte"] = 0;
        }
        if (!("original" in $$source)) {
            this["original"] = "";
        }
        if (!("edited" in $$source)) {
            this["edited"] = "";
        }
        if (!("atBof" in $$source)) {
            this["atBof"] = false;
        }
        if (!("atEof" in $$source)) {
            this["atEof"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffWindow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffWindow($$parsedSource as Partial<DiffWindow>);
    }
}

/**
 * FileMeta describes a freshly opened file.
 */
export class FileMeta {
    "fileId": string;
    "path": string;
    "size": number;
    "encoding": string;
    "detected": string;
    "binary": boolean;

    /**
     * UTF-8/ASCII + LF: in-window editing allowed
     */
    "editable": boolean;

    /** Creates a new FileMeta instance. */
    constructor($$source: Partial<FileMeta> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = "";
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FileMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMeta($$parsedSource as Partial<FileMeta>);
    }
}

/**
 * FileStateResult is a cheap follow-tail poll. Milliseconds (rather than Unix
 * nanoseconds) keep the timestamp exactly representable by JavaScript.
 */
export class FileStateResult {
    "size": number;
    "modTimeUnixMillis": number;
    "sameOpenedFile": boolean;
    "changedFromOpen": boolean;

    /** Creates a new FileStateResult instance. */
    constructor($$source: Partial<FileStateResult> = {}) {
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTimeUnixMillis" in $$source)) {
            this["modTimeUnixMillis"] = 0;
        }
        if (!("sameOpenedFile" in $$source)) {
            this["sameOpenedFile"] = false;
        }
        if (!("changedFromOpen" in $$source)) {
            this["changedFromOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileStateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStateResult($$parsedSource as Partial<FileStateResult>);
    }
}

/**
 * HexLine is one 16-byte row: global offset, space-grouped hex, and ASCII.
 */
export class HexLine {
    "offset": number;
    "hex": string;
    "ascii": string;

    /** Creates a new HexLine instance. */
    constructor($$source: Partial<HexLine> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("ascii" in $$source)) {
            this["ascii"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HexLine instance from a string or object.
     */
    static createFrom($$source: any = {}): HexLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HexLine($$parsedSource as Partial<HexLine>);
    }
}

/**
 * HexWindow is a bounded, 16-byte-aligned slice rendered as hex+ASCII.
 */
export class HexWindow {
    "fileId": string;
    "startByte": number;
    "nextByte": number;
    "lines": HexLine[];
    "atBof": boolean;
    "atEof": boolean;

    /** Creates a new HexWindow instance. */
    constructor($$source: Partial<HexWindow> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("startByte" in $$source)) {
            this["startByte"] = 0;
        }
        if (!("nextByte" in $$source)) {
            this["nextByte"] = 0;
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("atBof" in $$source)) {
            this["atBof"] = false;
        }
        if (!("atEof" in $$source)) {
            this["atEof"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HexWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): HexWindow {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField3_0($$parsedSource["lines"]);
        }
        return new HexWindow($$parsedSource as Partial<HexWindow>);
    }
}

/**
 * LineResolution distinguishes a real offset zero, an approximate known line
 * start, a line proven absent, an incomplete index, and a bounded-scan fallback.
 * When Exact is false and Found is true, ResolvedLine is the actual line at
 * Offset; it must not be mistaken for proof that the requested line was found.
 */
export class LineResolution {
    "offset": number;
    "resolvedLine": number;
    "exact": boolean;
    "found": boolean;
    "indexComplete": boolean;
    "limited": boolean;

    /** Creates a new LineResolution instance. */
    constructor($$source: Partial<LineResolution> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("resolvedLine" in $$source)) {
            this["resolvedLine"] = 0;
        }
        if (!("exact" in $$source)) {
            this["exact"] = false;
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("indexComplete" in $$source)) {
            this["indexComplete"] = false;
        }
        if (!("limited" in $$source)) {
            this["limited"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineResolution instance from a string or object.
     */
    static createFrom($$source: any = {}): LineResolution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LineResolution($$parsedSource as Partial<LineResolution>);
    }
}

/**
 * MatchWindow resolves a raw search match to exact CodeMirror UTF-16 code-unit
 * coordinates in one bounded decoded window.
 */
export class MatchWindow {
    "window": Window;
    "found": boolean;
    "from": number;
    "to": number;

    /** Creates a new MatchWindow instance. */
    constructor($$source: Partial<MatchWindow> = {}) {
        if (!("window" in $$source)) {
            this["window"] = (new Window());
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("from" in $$source)) {
            this["from"] = 0;
        }
        if (!("to" in $$source)) {
            this["to"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchWindow {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField0_0($$parsedSource["window"]);
        }
        return new MatchWindow($$parsedSource as Partial<MatchWindow>);
    }
}

/**
 * SaveResult describes a completed save.
 */
export class SaveResult {
    /**
     * "patch" | "copy"
     */
    "mode": string;
    "bytesWritten": number;
    "outputPath": string;

    /** Creates a new SaveResult instance. */
    constructor($$source: Partial<SaveResult> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("bytesWritten" in $$source)) {
            this["bytesWritten"] = 0;
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult($$parsedSource as Partial<SaveResult>);
    }
}

/**
 * SearchAllHit is one match in a whole-file search, with a preview line.
 */
export class SearchAllHit {
    "offset": number;
    "length": number;
    "line": number;
    "preview": string;

    /** Creates a new SearchAllHit instance. */
    constructor($$source: Partial<SearchAllHit> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchAllHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchAllHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchAllHit($$parsedSource as Partial<SearchAllHit>);
    }
}

/**
 * SearchAllResult holds up to MaxHits matches plus a truncation flag.
 */
export class SearchAllResult {
    "hits": SearchAllHit[];
    "truncated": boolean;
    "timedOut": boolean;
    "unsupported": boolean;
    "message": string;

    /** Creates a new SearchAllResult instance. */
    constructor($$source: Partial<SearchAllResult> = {}) {
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("timedOut" in $$source)) {
            this["timedOut"] = false;
        }
        if (!("unsupported" in $$source)) {
            this["unsupported"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchAllResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchAllResult {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField0_0($$parsedSource["hits"]);
        }
        return new SearchAllResult($$parsedSource as Partial<SearchAllResult>);
    }
}

/**
 * SearchHit is one match (or a not-found / timed-out / unsupported result).
 */
export class SearchHit {
    "found": boolean;
    "offset": number;
    "length": number;

    /**
     * approximate until the index is built
     */
    "line": number;

    /**
     * search hit the time budget before finishing
     */
    "timedOut": boolean;

    /**
     * Unsupported is set when the query can't be searched in the file's encoding
     * (e.g. regex over a UTF-16/Windows-125x file, or a term with characters not
     * representable in that encoding) — so the UI can say so instead of "no matches".
     */
    "unsupported": boolean;
    "message": string;

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("timedOut" in $$source)) {
            this["timedOut"] = false;
        }
        if (!("unsupported" in $$source)) {
            this["unsupported"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

/**
 * SqlLintFinding is one issue found in a dump.
 */
export class SqlLintFinding {
    /**
     * info | warn
     */
    "severity": string;
    "title": string;
    "detail": string;

    /** Creates a new SqlLintFinding instance. */
    constructor($$source: Partial<SqlLintFinding> = {}) {
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlLintFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlLintFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SqlLintFinding($$parsedSource as Partial<SqlLintFinding>);
    }
}

/**
 * SqlLintResult is the dump-linter output (derived from the cached analysis).
 */
export class SqlLintResult {
    "findings": SqlLintFinding[];

    /** Creates a new SqlLintResult instance. */
    constructor($$source: Partial<SqlLintResult> = {}) {
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlLintResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlLintResult {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField0_0($$parsedSource["findings"]);
        }
        return new SqlLintResult($$parsedSource as Partial<SqlLintResult>);
    }
}

/**
 * SqlSchemaDiffResult is the structural diff between two dumps.
 */
export class SqlSchemaDiffResult {
    "fileA": string;
    "fileB": string;
    "addedTables": string[];
    "removedTables": string[];
    "changedTables": schemadiff$0.TableDiff[];
    "unchangedCount": number;

    /** Creates a new SqlSchemaDiffResult instance. */
    constructor($$source: Partial<SqlSchemaDiffResult> = {}) {
        if (!("fileA" in $$source)) {
            this["fileA"] = "";
        }
        if (!("fileB" in $$source)) {
            this["fileB"] = "";
        }
        if (!("addedTables" in $$source)) {
            this["addedTables"] = [];
        }
        if (!("removedTables" in $$source)) {
            this["removedTables"] = [];
        }
        if (!("changedTables" in $$source)) {
            this["changedTables"] = [];
        }
        if (!("unchangedCount" in $$source)) {
            this["unchangedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlSchemaDiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlSchemaDiffResult {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addedTables" in $$parsedSource) {
            $$parsedSource["addedTables"] = $$createField2_0($$parsedSource["addedTables"]);
        }
        if ("removedTables" in $$parsedSource) {
            $$parsedSource["removedTables"] = $$createField3_0($$parsedSource["removedTables"]);
        }
        if ("changedTables" in $$parsedSource) {
            $$parsedSource["changedTables"] = $$createField4_0($$parsedSource["changedTables"]);
        }
        return new SqlSchemaDiffResult($$parsedSource as Partial<SqlSchemaDiffResult>);
    }
}

/**
 * SqlSummaryResult is the result of analysing a SQL dump.
 */
export class SqlSummaryResult {
    "tables": SqlTable[];
    "createTables": number;
    "insertTables": number;
    "definerCount": number;
    "header": boolean;

    /** Creates a new SqlSummaryResult instance. */
    constructor($$source: Partial<SqlSummaryResult> = {}) {
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("createTables" in $$source)) {
            this["createTables"] = 0;
        }
        if (!("insertTables" in $$source)) {
            this["insertTables"] = 0;
        }
        if (!("definerCount" in $$source)) {
            this["definerCount"] = 0;
        }
        if (!("header" in $$source)) {
            this["header"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlSummaryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlSummaryResult {
        const $$createField0_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField0_0($$parsedSource["tables"]);
        }
        return new SqlSummaryResult($$parsedSource as Partial<SqlSummaryResult>);
    }
}

/**
 * SqlTable is one discovered table in a dump.
 */
export class SqlTable {
    "name": string;
    "createOffset": number;
    "insertOffset": number;

    /**
     * approx byte size of the table's region in the dump
     */
    "bytes": number;

    /** Creates a new SqlTable instance. */
    constructor($$source: Partial<SqlTable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createOffset" in $$source)) {
            this["createOffset"] = 0;
        }
        if (!("insertOffset" in $$source)) {
            this["insertOffset"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlTable instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlTable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SqlTable($$parsedSource as Partial<SqlTable>);
    }
}

/**
 * StagedEdit is one pending edit, anchored to the original source, with short
 * before/after previews for the diff panel.
 */
export class StagedEdit {
    "start": number;
    "end": number;
    "line": number;
    "old": string;
    "new": string;

    /** Creates a new StagedEdit instance. */
    constructor($$source: Partial<StagedEdit> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("old" in $$source)) {
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            this["new"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StagedEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): StagedEdit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StagedEdit($$parsedSource as Partial<StagedEdit>);
    }
}

/**
 * StagingState summarizes pending edits and which save modes are available.
 */
export class StagingState {
    "editCount": number;
    "originalSize": number;
    "editedSize": number;
    "netDelta": number;
    "lengthPreserving": boolean;
    "inPlaceEligible": boolean;

    /** Creates a new StagingState instance. */
    constructor($$source: Partial<StagingState> = {}) {
        if (!("editCount" in $$source)) {
            this["editCount"] = 0;
        }
        if (!("originalSize" in $$source)) {
            this["originalSize"] = 0;
        }
        if (!("editedSize" in $$source)) {
            this["editedSize"] = 0;
        }
        if (!("netDelta" in $$source)) {
            this["netDelta"] = 0;
        }
        if (!("lengthPreserving" in $$source)) {
            this["lengthPreserving"] = false;
        }
        if (!("inPlaceEligible" in $$source)) {
            this["inPlaceEligible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StagingState instance from a string or object.
     */
    static createFrom($$source: any = {}): StagingState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StagingState($$parsedSource as Partial<StagingState>);
    }
}

export class TransformResult {
    "outputPath": string;
    "recordsRead": number;
    "recordsWritten": number;
    "note": string;

    /** Creates a new TransformResult instance. */
    constructor($$source: Partial<TransformResult> = {}) {
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("recordsRead" in $$source)) {
            this["recordsRead"] = 0;
        }
        if (!("recordsWritten" in $$source)) {
            this["recordsWritten"] = 0;
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransformResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TransformResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransformResult($$parsedSource as Partial<TransformResult>);
    }
}

/**
 * Window is a bounded, line-aligned slice of the file decoded to UTF-8, plus
 * the per-line global coordinates the editor gutter needs.
 */
export class Window {
    "fileId": string;

    /**
     * global byte offset of the first line
     */
    "startByte": number;

    /**
     * feed to GetNextWindow to continue
     */
    "nextByte": number;

    /**
     * lines joined with "\n"
     */
    "text": string;

    /**
     * global byte offset per line
     */
    "lineOffsets": number[];

    /**
     * global line number per line (approx until indexed)
     */
    "lineNumbers": number[];
    "atBof": boolean;
    "atEof": boolean;

    /**
     * line numbers are approximate (index not ready)
     */
    "approx": boolean;

    /** Creates a new Window instance. */
    constructor($$source: Partial<Window> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("startByte" in $$source)) {
            this["startByte"] = 0;
        }
        if (!("nextByte" in $$source)) {
            this["nextByte"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("lineOffsets" in $$source)) {
            this["lineOffsets"] = [];
        }
        if (!("lineNumbers" in $$source)) {
            this["lineNumbers"] = [];
        }
        if (!("atBof" in $$source)) {
            this["atBof"] = false;
        }
        if (!("atEof" in $$source)) {
            this["atEof"] = false;
        }
        if (!("approx" in $$source)) {
            this["approx"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Window instance from a string or object.
     */
    static createFrom($$source: any = {}): Window {
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lineOffsets" in $$parsedSource) {
            $$parsedSource["lineOffsets"] = $$createField4_0($$parsedSource["lineOffsets"]);
        }
        if ("lineNumbers" in $$parsedSource) {
            $$parsedSource["lineNumbers"] = $$createField5_0($$parsedSource["lineNumbers"]);
        }
        return new Window($$parsedSource as Partial<Window>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CsvDelimiterOption.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = csv$0.ColumnProfile.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = CsvColumn.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = CsvSqlColumnConfig.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = HexLine.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = Window.createFrom;
const $$createType13 = SearchAllHit.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = SqlLintFinding.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = schemadiff$0.TableDiff.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = SqlTable.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Array($Create.Any);
