// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Column describes one column of a table.
 */
export class Column {
    "name": string;
    "type": string;
    "nullable": boolean;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * DeleteProfileResult distinguishes a forward-committed deletion from an
 * ordinary pre-publication failure without exposing credential material.
 */
export class DeleteProfileResult {
    "deleted": boolean;
    "finalizationWarning": string;

    /** Creates a new DeleteProfileResult instance. */
    constructor($$source: Partial<DeleteProfileResult> = {}) {
        if (!("deleted" in $$source)) {
            this["deleted"] = false;
        }
        if (!("finalizationWarning" in $$source)) {
            this["finalizationWarning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteProfileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteProfileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteProfileResult($$parsedSource as Partial<DeleteProfileResult>);
    }
}

/**
 * Profile is a saved connection. Password is input-only (json omitempty) and is
 * never persisted or returned — it is moved into the secret store on save.
 */
export class Profile {
    "id": string;
    "name": string;

    /**
     * sqlite | postgres | mysql
     */
    "kind": string;

    /**
     * sqlite
     */
    "file": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;

    /**
     * transport mode for postgres + mysql; empty = secure-by-default (see resolveTLS)
     */
    "sslMode": string;

    /**
     * output-only backend-owned profile/scope handle; caller input is ignored
     */
    "secretRef": string;

    /**
     * input only — never persisted
     */
    "password"?: string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("secretRef" in $$source)) {
            this["secretRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

/**
 * ProfileCredentialStatus is a fail-closed, non-secret description of whether
 * the credential referenced by a profile can actually be used. The renderer
 * must not infer this from SecretRef alone: a retained ref may be quarantined
 * legacy evidence, missing, or unreadable while the encrypted store is ill.
 */
export class ProfileCredentialStatus {
    "profileId": string;

    /**
     * non-secret correlation handle already present on Profile
     */
    "secretRef": string;

    /**
     * none | verified | quarantined | unavailable
     */
    "status": string;

    /** Creates a new ProfileCredentialStatus instance. */
    constructor($$source: Partial<ProfileCredentialStatus> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("secretRef" in $$source)) {
            this["secretRef"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileCredentialStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileCredentialStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileCredentialStatus($$parsedSource as Partial<ProfileCredentialStatus>);
    }
}

/**
 * QueryResult is a read-only query's columns + stringified rows. Nulls is a mask
 * parallel to Rows marking which cells were SQL NULL, so the UI can distinguish a
 * real NULL from the literal text "NULL" out-of-band (not by string compare).
 */
export class QueryResult {
    "columns": string[];
    "rows": string[][];
    "nulls": boolean[][];
    "rowCount": number;
    "truncated": boolean;

    /**
     * TruncationReason is "row_limit" or "byte_limit" when Truncated is true.
     * Column-count and per-cell violations are errors instead of partial success.
     */
    "truncationReason": string;
    "elapsedMs": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("nulls" in $$source)) {
            this["nulls"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("truncationReason" in $$source)) {
            this["truncationReason"] = "";
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("nulls" in $$parsedSource) {
            $$parsedSource["nulls"] = $$createField2_0($$parsedSource["nulls"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * SaveProfileResult preserves the backend-issued identity even when the
 * profile replacement was published but directory finalization failed. A
 * non-empty FinalizationWarning means the visible state is forward-committed,
 * but durability is uncertain and further mutations are blocked.
 */
export class SaveProfileResult {
    "profile": Profile;
    "finalizationWarning": string;

    /** Creates a new SaveProfileResult instance. */
    constructor($$source: Partial<SaveProfileResult> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = (new Profile());
        }
        if (!("finalizationWarning" in $$source)) {
            this["finalizationWarning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveProfileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveProfileResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        return new SaveProfileResult($$parsedSource as Partial<SaveProfileResult>);
    }
}

/**
 * Table is a schema object listed for a connection.
 */
export class Table {
    "schema": string;
    "name": string;
    "type": string;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Table($$parsedSource as Partial<Table>);
    }
}

/**
 * TestResult reports a connectivity check.
 */
export class TestResult {
    "ok": boolean;
    "message": string;

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Profile.createFrom;
