// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Diagnostic is one static finding (a TODO-style marker or a merge conflict).
 */
export class Diagnostic {
    "path": string;
    "line": number;
    "column": number;

    /**
     * error | warning | info
     */
    "severity": string;

    /**
     * TODO | FIXME | HACK | XXX | conflict
     */
    "kind": string;
    "message": string;

    /** Creates a new Diagnostic instance. */
    constructor($$source: Partial<Diagnostic> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): Diagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostic($$parsedSource as Partial<Diagnostic>);
    }
}

/**
 * DiagnosticsResult is the outcome of a static workspace scan.
 */
export class DiagnosticsResult {
    "items": Diagnostic[];
    "fileCount": number;
    "truncated": boolean;

    /** Creates a new DiagnosticsResult instance. */
    constructor($$source: Partial<DiagnosticsResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticsResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new DiagnosticsResult($$parsedSource as Partial<DiagnosticsResult>);
    }
}

/**
 * DumpExtractResult reports the outputs of a dump extract/split.
 */
export class DumpExtractResult {
    /**
     * workspace-relative output paths
     */
    "outputs": string[];
    "tables": number;
    "bytes": number;

    /** Creates a new DumpExtractResult instance. */
    constructor($$source: Partial<DumpExtractResult> = {}) {
        if (!("outputs" in $$source)) {
            this["outputs"] = [];
        }
        if (!("tables" in $$source)) {
            this["tables"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpExtractResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DumpExtractResult {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outputs" in $$parsedSource) {
            $$parsedSource["outputs"] = $$createField0_0($$parsedSource["outputs"]);
        }
        return new DumpExtractResult($$parsedSource as Partial<DumpExtractResult>);
    }
}

/**
 * Entry is a single directory child, used to build the file tree lazily.
 */
export class Entry {
    "name": string;

    /**
     * slash-separated, relative to root
     */
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * unix milliseconds
     */
    "modTime": number;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

/**
 * FileChunk is one byte-range page of a file, for the read-only viewer that
 * handles files too large for the editor. Only the requested window is read
 * into memory — never the whole file.
 */
export class FileChunk {
    "path": string;

    /**
     * byte offset of this page
     */
    "offset": number;

    /**
     * bytes actually returned
     */
    "length": number;

    /**
     * total file size in bytes
     */
    "total": number;

    /**
     * this page reaches the end of the file
     */
    "eof": boolean;

    /**
     * the file looks binary (sniffed from its head)
     */
    "binary": boolean;

    /**
     * UTF-8 text page (empty when Binary)
     */
    "text": string;

    /**
     * canonical hex dump (only when Binary)
     */
    "hex": string;

    /** Creates a new FileChunk instance. */
    constructor($$source: Partial<FileChunk> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("eof" in $$source)) {
            this["eof"] = false;
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChunk($$parsedSource as Partial<FileChunk>);
    }
}

/**
 * FileContent is the result of reading a file for the editor.
 */
export class FileContent {
    "path": string;
    "content": string;

    /**
     * sha256 of on-disk bytes
     */
    "revision": string;
    "truncated": boolean;
    "binary": boolean;
    "tooLarge": boolean;
    "size": number;

    /**
     * Encoding is the detected on-disk text encoding (utf-8, utf-8-bom, utf-16le,
     * utf-16be, latin-1). Content is always UTF-8; this tells the UI when the file
     * was not UTF-8 so it can warn and round-trip the encoding on save.
     */
    "encoding": string;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("tooLarge" in $$source)) {
            this["tooLarge"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

/**
 * Info describes the currently open workspace.
 */
export class Info {
    "root": string;
    "name": string;
    "isOpen": boolean;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isOpen" in $$source)) {
            this["isOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * SearchMatch is one matching line.
 */
export class SearchMatch {
    "path": string;

    /**
     * 1-based
     */
    "line": number;

    /**
     * 1-based, rune index
     */
    "column": number;
    "text": string;

    /** Creates a new SearchMatch instance. */
    constructor($$source: Partial<SearchMatch> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchMatch($$parsedSource as Partial<SearchMatch>);
    }
}

/**
 * SearchResult is the outcome of a workspace text search.
 */
export class SearchResult {
    "matches": SearchMatch[];
    "fileCount": number;
    "truncated": boolean;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField0_0($$parsedSource["matches"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * TableInfoResult reports a tabular file's data-row count (for the virtual
 * scrollbar) and whether a sparse offset index is available (fast random jumps).
 */
export class TableInfoResult {
    /**
     * data rows (excludes the header)
     */
    "rows": number;

    /**
     * sparse byte-offset index built (CSV/TSV)
     */
    "indexed": boolean;

    /** Creates a new TableInfoResult instance. */
    constructor($$source: Partial<TableInfoResult> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("indexed" in $$source)) {
            this["indexed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfoResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfoResult($$parsedSource as Partial<TableInfoResult>);
    }
}

/**
 * TablePage is one window of a tabular file.
 */
export class TablePage {
    "path": string;
    "sheet": string;
    "columns": string[];
    "rows": string[][];
    "offset": number;

    /**
     * more rows after this window (current filter/sort)
     */
    "hasMore": boolean;

    /**
     * -1 when unknown (browse mode); else matched count
     */
    "totalRows": number;

    /**
     * the filtered/sorted set hit tableResultCap
     */
    "capped": boolean;

    /**
     * delimiter actually used (comma|semicolon|tab|pipe); "" for XLSX
     */
    "delimiter": string;
    "message": string;

    /** Creates a new TablePage instance. */
    constructor($$source: Partial<TablePage> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sheet" in $$source)) {
            this["sheet"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }
        if (!("totalRows" in $$source)) {
            this["totalRows"] = 0;
        }
        if (!("capped" in $$source)) {
            this["capped"] = false;
        }
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TablePage instance from a string or object.
     */
    static createFrom($$source: any = {}): TablePage {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        return new TablePage($$parsedSource as Partial<TablePage>);
    }
}

/**
 * TableQuery selects a window of a tabular file, optionally filtered/sorted over
 * the WHOLE file. A blank filter and SortCol < 0 means plain windowed browsing
 * (only the window is read off disk — no full scan).
 */
export class TableQuery {
    "offset": number;
    "limit": number;

    /**
     * case-insensitive substring across cells; "" = none
     */
    "filter": string;

    /**
     * -1 = no sort
     */
    "sortCol": number;

    /**
     * 1 asc, -1 desc
     */
    "sortDir": number;

    /**
     * "" = auto-detect; else comma|semicolon|tab|pipe (CSV/TSV)
     */
    "delimiter": string;

    /** Creates a new TableQuery instance. */
    constructor($$source: Partial<TableQuery> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("sortCol" in $$source)) {
            this["sortCol"] = 0;
        }
        if (!("sortDir" in $$source)) {
            this["sortDir"] = 0;
        }
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): TableQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableQuery($$parsedSource as Partial<TableQuery>);
    }
}

/**
 * WriteResult is returned after a successful write and carries the new revision
 * so the editor can keep its optimistic-concurrency token current.
 */
export class WriteResult {
    "path": string;
    "revision": string;

    /** Creates a new WriteResult instance. */
    constructor($$source: Partial<WriteResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteResult($$parsedSource as Partial<WriteResult>);
    }
}

// Private type creation functions
const $$createType0 = Diagnostic.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = SearchMatch.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType2);
