// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails watcher service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Suppress marks an absolute path as about-to-be-written by Novera itself, so
 * the fs event(s) the write produces are not reported back to the UI as an
 * external change. Called by the workspace service just before an atomic save.
 */
export function Suppress(abs: string): $CancellablePromise<void> {
    return $Call.ByID(2995329593, abs);
}

/**
 * Watch sets the workspace-relative files to monitor (the open editor tabs).
 * It (re)watches their parent directories and drops directories no longer needed.
 */
export function Watch(rels: string[]): $CancellablePromise<void> {
    return $Call.ByID(3386639061, rels);
}
