// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes streaming, windowed access to very large files. It is
 * bound to the frontend by Wails; the whole-file content never crosses the
 * bridge — only bounded, line-aligned windows do.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginSearchRequest reserves one bounded, server-owned cancellation identity.
 * The reservation expires after searchTimeout even if the frontend abandons it.
 * Call exactly one *Request method or CancelSearch for each returned ID.
 */
export function BeginSearchRequest(fileID: string): $CancellablePromise<string> {
    return $Call.ByID(3683175542, fileID);
}

/**
 * CancelJob cancels exactly the active job represented by jobID. A stale ID is
 * rejected and cannot cancel a newer operation.
 */
export function CancelJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2867360005, jobID);
}

/**
 * CancelSearch cancels only the exact active ID. IDs are monotonically
 * generated and never reused, so a delayed cancellation cannot hit newer work.
 */
export function CancelSearch(requestID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3389175066, requestID);
}

/**
 * CloseFile releases a file's resources.
 */
export function CloseFile(fileID: string): $CancellablePromise<void> {
    return $Call.ByID(1864103002, fileID);
}

/**
 * CsvAddColumnViaDialog writes a new CSV with a constant column appended to every
 * row (including the header, which becomes the value).
 */
export function CsvAddColumnViaDialog(fileID: string, sourceGeneration: number, delimiter: string, columnCount: number, value: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1110146483, fileID, sourceGeneration, delimiter, columnCount, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvDedupeViaDialog writes a new CSV dropping duplicate rows — by a key column
 * (keyColumn>=0) or the whole row (keyColumn<0). First occurrence wins.
 */
export function CsvDedupeViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, keyColumn: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1348673393, fileID, sourceGeneration, delimiter, hasHeader, keyColumn).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportJSONLViaDialog streams the CSV to newline-delimited JSON.
 */
export function CsvExportJSONLViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, numberKeys: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(724714548, fileID, sourceGeneration, delimiter, hasHeader, numberKeys).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportSQLiteViaDialog is disabled until SQLite publication can provide
 * the same atomic, no-overwrite guarantees as the other artifact transforms.
 */
export function CsvExportSQLiteViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, tableName: string, typedCells: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1436630870, fileID, sourceGeneration, delimiter, hasHeader, tableName, typedCells).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvExportXLSXViaDialog is disabled until workbook generation can use secure,
 * exclusively owned scratch storage.
 */
export function CsvExportXLSXViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, sheetName: string, typedCells: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2750541179, fileID, sourceGeneration, delimiter, hasHeader, sheetName, typedCells).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvFilterViaDialog writes a new CSV keeping only rows where the chosen column
 * matches op/value (eq, ne, contains, gt, lt, empty, nonempty). Source untouched.
 */
export function CsvFilterViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, column: number, op: string, value: string, negate: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2426919946, fileID, sourceGeneration, delimiter, hasHeader, column, op, value, negate).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvInspect detects the most likely delimiter (and ranked alternatives) from a
 * bounded sample, so the UI can preselect it and offer overrides.
 */
export function CsvInspect(fileID: string): $CancellablePromise<$models.CsvInspectResult> {
    return $Call.ByID(792128788, fileID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CsvMarkdownPreview returns the current preview as a Markdown table (for copy).
 */
export function CsvMarkdownPreview(fileID: string, delimiter: string, hasHeader: boolean, maxRows: number): $CancellablePromise<$models.CsvTextPreviewResult> {
    return $Call.ByID(403569035, fileID, delimiter, hasHeader, maxRows).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CsvPreview(fileID: string, delimiter: string, hasHeader: boolean, maxRows: number): $CancellablePromise<$models.CsvPreviewResult> {
    return $Call.ByID(1308065476, fileID, delimiter, hasHeader, maxRows).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CsvProfile profiles each column (null %, distinct, min/max, top values) and
 * counts ragged rows over a bounded sample.
 */
export function CsvProfile(fileID: string, delimiter: string, hasHeader: boolean): $CancellablePromise<$models.CsvProfileResult> {
    return $Call.ByID(3488062821, fileID, delimiter, hasHeader).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CsvProjectViaDialog writes a new CSV keeping only keepIndices (0-based) in the
 * given order — used for drop-column and reorder.
 */
export function CsvProjectViaDialog(fileID: string, sourceGeneration: number, delimiter: string, keepIndices: number[]): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(165873055, fileID, sourceGeneration, delimiter, keepIndices).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvRedactViaDialog writes an anonymized copy of the CSV with the chosen columns
 * masked, for sharing a dataset without leaking PII. Source is never modified.
 */
export function CsvRedactViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, columns: $models.CsvRedactColumn[], replacement: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3188274975, fileID, sourceGeneration, delimiter, hasHeader, columns, replacement).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvSampleViaDialog writes a new CSV keeping every Nth data row (header kept),
 * for shrinking a huge dump to a representative slice.
 */
export function CsvSampleViaDialog(fileID: string, sourceGeneration: number, delimiter: string, hasHeader: boolean, everyN: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3744408314, fileID, sourceGeneration, delimiter, hasHeader, everyN).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CsvSchema(fileID: string, delimiter: string, hasHeader: boolean): $CancellablePromise<$models.CsvSchemaResult> {
    return $Call.ByID(3148189243, fileID, delimiter, hasHeader).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CsvToSQLConfigPreview returns a short sample of the SQL for a full config.
 */
export function CsvToSQLConfigPreview(fileID: string, cfg: $models.CsvSqlConfig): $CancellablePromise<$models.CsvTextPreviewResult> {
    return $Call.ByID(710905099, fileID, cfg).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CsvToSQLConfigViaDialog streams the whole CSV to a .sql file using a full
 * column-mapping config (select/rename/type, insert mode, batch, null, policy).
 */
export function CsvToSQLConfigViaDialog(fileID: string, sourceGeneration: number, cfg: $models.CsvSqlConfig): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3756880875, fileID, sourceGeneration, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CsvToSQLPreview returns a short sample of the generated SQL.
 */
export function CsvToSQLPreview(fileID: string, delimiter: string, tableName: string, hasHeader: boolean, includeCreate: boolean): $CancellablePromise<$models.CsvTextPreviewResult> {
    return $Call.ByID(3439646149, fileID, delimiter, tableName, hasHeader, includeCreate).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CsvToSQLViaDialog streams the whole CSV to a .sql file of INSERTs.
 */
export function CsvToSQLViaDialog(fileID: string, sourceGeneration: number, delimiter: string, tableName: string, hasHeader: boolean, includeCreate: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(428322317, fileID, sourceGeneration, delimiter, tableName, hasHeader, includeCreate).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiscardEdits drops all staged edits.
 */
export function DiscardEdits(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(3793258711, fileID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * FileSize re-stats the file on disk and returns its current size. Cheap — used
 * to poll a growing file (tail/follow) without reopening it.
 */
export function FileSize(fileID: string): $CancellablePromise<number> {
    return $Call.ByID(1707831887, fileID);
}

/**
 * FileState returns the pathname's current state and whether it still names
 * the exact retained descriptor. This detects rename-and-recreate rotation,
 * including replacements with the same size and modification time.
 */
export function FileState(fileID: string): $CancellablePromise<$models.FileStateResult> {
    return $Call.ByID(907552787, fileID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function FindNextRequest(requestID: string, query: string, fromByte: number, regex: boolean, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchHit> {
    return $Call.ByID(1229834119, requestID, query, fromByte, regex, caseSensitive, wholeWord).then(($result: any) => {
        return $$createType8($result);
    });
}

export function FindPrevRequest(requestID: string, query: string, beforeByte: number, regex: boolean, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchHit> {
    return $Call.ByID(289346419, requestID, query, beforeByte, regex, caseSensitive, wholeWord).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetCsvGrid parses a bounded raw-byte window into complete logical CSV
 * records. startByte must be zero or a NextByte returned by an earlier call for
 * the same file generation and delimiter. Physical newlines inside quoted
 * fields never become cursors.
 */
export function GetCsvGrid(fileID: string, delimiter: string, startByte: number, maxBytes: number): $CancellablePromise<$models.CsvGridResult> {
    return $Call.ByID(885416396, fileID, delimiter, startByte, maxBytes).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetDiffWindow returns the edited and original text for a line-aligned window,
 * for the side-by-side diff view.
 */
export function GetDiffWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.DiffWindow> {
    return $Call.ByID(2293174843, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetEditWindow returns a byte-exact, line-aligned UTF-8 window that reflects
 * staged edits (reads the edited view when edits exist, else the raw document).
 * startByte is aligned down to a line start; pass any byte for go-to / prev.
 */
export function GetEditWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(2343628796, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetHexWindow returns a bounded hex dump of the file starting at (16-byte
 * aligned) startByte. Scrolling loads adjacent windows; the file is never fully
 * read. Works for any file, including binary.
 */
export function GetHexWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.HexWindow> {
    return $Call.ByID(914678545, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetMatchWindow returns a bounded decoded window that contains hitOffset and,
 * when the complete hit is displayable, its exact JavaScript UTF-16 span.
 */
export function GetMatchWindow(fileID: string, hitOffset: number, hitLength: number, maxBytes: number): $CancellablePromise<$models.MatchWindow> {
    return $Call.ByID(2704531653, fileID, hitOffset, hitLength, maxBytes).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetNextWindow continues forward from a previous window's NextByte.
 */
export function GetNextWindow(fileID: string, fromByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(3363176709, fileID, fromByte, maxBytes).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetPrevWindow returns the bounded decoded window immediately preceding
 * currentStart. Its NextByte is exactly currentStart.
 */
export function GetPrevWindow(fileID: string, currentStart: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(1960744817, fileID, currentStart, maxBytes).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetStagedEdits returns the pending edits (source-anchored) for the diff panel.
 */
export function GetStagedEdits(fileID: string): $CancellablePromise<$models.StagedEdit[]> {
    return $Call.ByID(1432012583, fileID).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetStagingState reports current pending-edit status.
 */
export function GetStagingState(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(2175041062, fileID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTailWindow returns the final non-empty bounded window ending at the
 * retained generation's EOF. An empty source honestly returns an empty
 * BOF/EOF window.
 */
export function GetTailWindow(fileID: string, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(4038850250, fileID, maxBytes).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetWindow returns a bounded, decoded window beginning at the line that
 * contains startByte.
 */
export function GetWindow(fileID: string, startByte: number, maxBytes: number): $CancellablePromise<$models.Window> {
    return $Call.ByID(2814923928, fileID, startByte, maxBytes).then(($result: any) => {
        return $$createType11($result);
    });
}

export function HarvestMatchesViaDialog(fileID: string, pattern: string, caseInsensitive: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(4019629850, fileID, pattern, caseInsensitive).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenFile opens path, starts background indexing, and returns its metadata.
 * Opening a file is intentionally non-mutating: adjacent recovery artifacts
 * are left untouched for an explicit, user-confirmed recovery workflow.
 */
export function OpenFile(path: string): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(382069238, path).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * OpenViaDialog shows a native open-file dialog and opens the chosen file. A
 * cancelled dialog returns an empty FileMeta (FileID == "") with a nil error.
 */
export function OpenViaDialog(): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(2517771520).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PrepareEditSession performs the one exact full-source fingerprint as a
 * cancellable, progress-reporting job before the frontend enables edit mode.
 * StageEdit never performs this whole-file pass.
 */
export function PrepareEditSession(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(4079740945, fileID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RefreshFile reloads the file from disk under the same id (fresh size + line
 * index), for following a growing file or picking up external changes. It
 * fails while edits are staged; discarding them requires the explicit
 * DiscardEdits operation.
 */
export function RefreshFile(fileID: string): $CancellablePromise<$models.FileMeta> {
    return $Call.ByID(1000304125, fileID).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ReleaseCleanEditSession drops the retained exact fingerprint only when no
 * staged edits exist. Dirty state is never discarded implicitly.
 */
export function ReleaseCleanEditSession(fileID: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(4030164182, fileID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ResolveLine maps a positive 1-based line number under a hard 8 MiB exact-scan
 * budget and a timeout. Source read failures remain errors; a timeout fallback
 * is returned explicitly and never reported as proof that the line is absent.
 */
export function ResolveLine(fileID: string, line: number): $CancellablePromise<$models.LineResolution> {
    return $Call.ByID(4183015142, fileID, line).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SaveCopyViaDialog shows a native save dialog and writes the edited copy there.
 * A cancelled dialog returns an empty SaveResult (Mode == "") with nil error.
 */
export function SaveCopyViaDialog(fileID: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1169867108, fileID).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * SavePatch is retained as an RPC compatibility boundary but fails closed.
 * Source mutation remains unavailable; callers must save a separate copy.
 */
export function SavePatch(fileID: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1419832985, fileID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SearchAllRequest(requestID: string, query: string, regex: boolean, caseSensitive: boolean, wholeWord: boolean, maxHits: number): $CancellablePromise<$models.SearchAllResult> {
    return $Call.ByID(1561391520, requestID, query, regex, caseSensitive, wholeWord, maxHits).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SqlAnalyze streams a single pass over the dump to discover tables and stats,
 * caching the result for later extraction. This is a full pass — the UI should
 * show progress for huge files.
 */
export function SqlAnalyze(fileID: string): $CancellablePromise<$models.SqlSummaryResult> {
    return $Call.ByID(1563764376, fileID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * SqlApplyPresetViaDialog is retained for generated-binding compatibility. It
 * rejects before file lookup, dialogs, jobs, or filesystem work.
 */
export function SqlApplyPresetViaDialog(fileID: string, name: string, a1: string, a2: string, a3: string, a4: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1655907585, fileID, name, a1, a2, a3, a4).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractDataViaDialog writes exact analyzed INSERT/REPLACE regions for one
 * table, with no DDL or surrounding dump SQL.
 */
export function SqlExtractDataViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(2269513535, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractSchemaViaDialog writes exact analyzed CREATE regions with no INSERT
 * data. An empty tableName selects every discovered table.
 */
export function SqlExtractSchemaViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1617829806, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlExtractTableViaDialog writes one table's exact analyzed
 * CREATE/INSERT/REPLACE regions to a chosen output file. Surrounding session
 * and unrelated SQL is deliberately omitted.
 */
export function SqlExtractTableViaDialog(fileID: string, tableName: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3125375737, fileID, tableName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlLint reports dump issues from the cached analysis: empty tables, DEFINER
 * usage, mixed charsets/collations, and the largest tables. No new file scan.
 */
export function SqlLint(fileID: string): $CancellablePromise<$models.SqlLintResult> {
    return $Call.ByID(3422427641, fileID).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * SqlListPresets exposes no names while structural cleanup presets remain
 * fail-closed.
 */
export function SqlListPresets(): $CancellablePromise<string[]> {
    return $Call.ByID(69917632).then(($result: any) => {
        return $$createType22($result);
    });
}

export function SqlReplaceViaDialog(fileID: string, find: string, replaceWith: string, regex: boolean, caseInsensitive: boolean, wholeWord: boolean): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(1077960636, fileID, find, replaceWith, regex, caseInsensitive, wholeWord).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlReshapeInsertsViaDialog rewrites INSERT row layout, streaming to a new file.
 * mode "single" explodes extended INSERTs into one row each (good for line diffs);
 * mode "multi" batches consecutive single-row INSERTs (good for fast re-import).
 */
export function SqlReshapeInsertsViaDialog(fileID: string, mode: string, batchSize: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3588725676, fileID, mode, batchSize).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlSampleFixtureViaDialog writes a small "dev fixture" dump: each table's DDL
 * plus only its first rowsPerTable INSERT rows. Turns a prod dump into a tiny,
 * shareable seed without ever materialising the whole file.
 */
export function SqlSampleFixtureViaDialog(fileID: string, rowsPerTable: number): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3698625949, fileID, rowsPerTable).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SqlSchemaDiff compares complete bounded CREATE TABLE structure for two
 * analyzed dumps (A = baseline, B = new), including constraints, indexes,
 * options, qualified identity, and column order.
 */
export function SqlSchemaDiff(fileIDA: string, fileIDB: string): $CancellablePromise<$models.SqlSchemaDiffResult> {
    return $Call.ByID(3883908852, fileIDA, fileIDB).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * SqlSplitByTableViaDialog writes one .sql file per table into a chosen folder.
 */
export function SqlSplitByTableViaDialog(fileID: string): $CancellablePromise<$models.TransformResult> {
    return $Call.ByID(3832893453, fileID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StageEdit reconciles the window [startByte, startByte+origLen) with newText.
 * It trims the common prefix/suffix so only the genuinely changed bytes are
 * staged, keeping the diff granular and in-place patches minimal.
 */
export function StageEdit(fileID: string, startByte: number, origLen: number, newText: string): $CancellablePromise<$models.StagingState> {
    return $Call.ByID(756414490, fileID, startByte, origLen, newText).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TransformResult.createFrom;
const $$createType1 = $models.CsvInspectResult.createFrom;
const $$createType2 = $models.CsvTextPreviewResult.createFrom;
const $$createType3 = $models.CsvPreviewResult.createFrom;
const $$createType4 = $models.CsvProfileResult.createFrom;
const $$createType5 = $models.CsvSchemaResult.createFrom;
const $$createType6 = $models.StagingState.createFrom;
const $$createType7 = $models.FileStateResult.createFrom;
const $$createType8 = $models.SearchHit.createFrom;
const $$createType9 = $models.CsvGridResult.createFrom;
const $$createType10 = $models.DiffWindow.createFrom;
const $$createType11 = $models.Window.createFrom;
const $$createType12 = $models.HexWindow.createFrom;
const $$createType13 = $models.MatchWindow.createFrom;
const $$createType14 = $models.StagedEdit.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.FileMeta.createFrom;
const $$createType17 = $models.LineResolution.createFrom;
const $$createType18 = $models.SaveResult.createFrom;
const $$createType19 = $models.SearchAllResult.createFrom;
const $$createType20 = $models.SqlSummaryResult.createFrom;
const $$createType21 = $models.SqlLintResult.createFrom;
const $$createType22 = $Create.Array($Create.Any);
const $$createType23 = $models.SqlSchemaDiffResult.createFrom;
