// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecretService is a compatibility facade for the existing generated frontend
 * binding. It intentionally exposes no generic store access: every operation is
 * constrained to the current backend-owned LLM credential scope.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DeleteKey removes only the current LLM credential.
 */
export function DeleteKey(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3461365121, ref);
}

/**
 * HasKey reports only the current LLM credential state.
 */
export function HasKey(ref: string): $CancellablePromise<boolean> {
    return $Call.ByID(2933307674, ref);
}

/**
 * ListKeys returns at most the current LLM-owned ref. Database and other
 * subsystem refs are never disclosed across the renderer boundary.
 */
export function ListKeys(): $CancellablePromise<string[]> {
    return $Call.ByID(3599981601).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetKey stores only the current LLM credential. Arbitrary caller-selected
 * references (including database credential refs) are rejected.
 */
export function SetKey(ref: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3505611642, ref, value);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
