// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails terminal service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close terminates a session (UI-initiated). No exit event is emitted — the UI
 * already knows it closed the panel.
 */
export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(1125763888, id);
}

/**
 * Resize updates the pseudo-terminal dimensions.
 */
export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2374016900, id, cols, rows);
}

/**
 * Start launches a shell on a new pseudo-terminal sized to cols×rows and returns
 * the session id. Output arrives via the "term:data" event.
 */
export function Start(cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1362006304, cols, rows);
}

/**
 * Write sends user input (keystrokes) to the session's shell. An unknown id is
 * treated as an already-closed session (no-op, nil error) — the same contract as
 * Resize and Close — so a late keystroke racing a restart isn't a hard error.
 */
export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(4177553243, id, data);
}
