// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DumpSummary inventories a SQL dump.
 */
export class DumpSummary {
    "tables": DumpTable[];

    /**
     * count of CREATE TABLE statements
     */
    "createTables": number;

    /**
     * count of INSERT INTO statements
     */
    "insertTables": number;

    /**
     * count of COPY … FROM stdin blocks (pg_dump)
     */
    "copyBlocks": number;
    "mysqldump": boolean;

    /**
     * stopped at the byte cap
     */
    "truncated": boolean;

    /** Creates a new DumpSummary instance. */
    constructor($$source: Partial<DumpSummary> = {}) {
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("createTables" in $$source)) {
            this["createTables"] = 0;
        }
        if (!("insertTables" in $$source)) {
            this["insertTables"] = 0;
        }
        if (!("copyBlocks" in $$source)) {
            this["copyBlocks"] = 0;
        }
        if (!("mysqldump" in $$source)) {
            this["mysqldump"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DumpSummary {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField0_0($$parsedSource["tables"]);
        }
        return new DumpSummary($$parsedSource as Partial<DumpSummary>);
    }
}

/**
 * DumpTable is a table discovered in a SQL dump.
 */
export class DumpTable {
    "name": string;

    /**
     * byte offset of CREATE TABLE, or -1
     */
    "createOffset": number;

    /**
     * byte offset of first INSERT INTO, or -1
     */
    "insertOffset": number;

    /** Creates a new DumpTable instance. */
    constructor($$source: Partial<DumpTable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createOffset" in $$source)) {
            this["createOffset"] = 0;
        }
        if (!("insertOffset" in $$source)) {
            this["insertOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpTable instance from a string or object.
     */
    static createFrom($$source: any = {}): DumpTable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DumpTable($$parsedSource as Partial<DumpTable>);
    }
}

/**
 * DumpTransform selects which cleanup transforms to apply to a SQL dump. Empty
 * string fields mean "leave unchanged".
 */
export class DumpTransform {
    /**
     * strip DEFINER=user@host clauses
     */
    "removeDefiner": boolean;

    /**
     * strip table-option AUTO_INCREMENT=N
     */
    "dropAutoIncrement": boolean;

    /**
     * rewrite ENGINE=… (e.g. "InnoDB")
     */
    "engine": string;

    /**
     * rewrite (DEFAULT) CHARSET/CHARACTER SET
     */
    "charset": string;

    /**
     * rewrite COLLATE …
     */
    "collation": string;

    /**
     * rename this database…
     */
    "fromDatabase": string;

    /**
     * …to this (both required for the rename)
     */
    "toDatabase": string;

    /** Creates a new DumpTransform instance. */
    constructor($$source: Partial<DumpTransform> = {}) {
        if (!("removeDefiner" in $$source)) {
            this["removeDefiner"] = false;
        }
        if (!("dropAutoIncrement" in $$source)) {
            this["dropAutoIncrement"] = false;
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("charset" in $$source)) {
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            this["collation"] = "";
        }
        if (!("fromDatabase" in $$source)) {
            this["fromDatabase"] = "";
        }
        if (!("toDatabase" in $$source)) {
            this["toDatabase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpTransform instance from a string or object.
     */
    static createFrom($$source: any = {}): DumpTransform {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DumpTransform($$parsedSource as Partial<DumpTransform>);
    }
}

/**
 * DumpTransformSummary reports a transform run.
 */
export class DumpTransformSummary {
    "bytesIn": number;
    "bytesOut": number;
    "replacements": number;

    /** Creates a new DumpTransformSummary instance. */
    constructor($$source: Partial<DumpTransformSummary> = {}) {
        if (!("bytesIn" in $$source)) {
            this["bytesIn"] = 0;
        }
        if (!("bytesOut" in $$source)) {
            this["bytesOut"] = 0;
        }
        if (!("replacements" in $$source)) {
            this["replacements"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpTransformSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DumpTransformSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DumpTransformSummary($$parsedSource as Partial<DumpTransformSummary>);
    }
}

/**
 * SQLConvertSummary reports how much was generated.
 */
export class SQLConvertSummary {
    "rows": number;
    "bytes": number;

    /** Creates a new SQLConvertSummary instance. */
    constructor($$source: Partial<SQLConvertSummary> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLConvertSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SQLConvertSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SQLConvertSummary($$parsedSource as Partial<SQLConvertSummary>);
    }
}

/**
 * SchemaColumn describes one inferred column.
 */
export class SchemaColumn {
    "name": string;

    /**
     * BIGINT | DOUBLE | BOOLEAN | TEXT
     */
    "type": string;
    "nonNull": number;
    "null": number;

    /**
     * up to 3 example values
     */
    "samples": string[];

    /** Creates a new SchemaColumn instance. */
    constructor($$source: Partial<SchemaColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nonNull" in $$source)) {
            this["nonNull"] = 0;
        }
        if (!("null" in $$source)) {
            this["null"] = 0;
        }
        if (!("samples" in $$source)) {
            this["samples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaColumn {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField4_0($$parsedSource["samples"]);
        }
        return new SchemaColumn($$parsedSource as Partial<SchemaColumn>);
    }
}

/**
 * SchemaResult is the inferred schema of a CSV/TSV file.
 */
export class SchemaResult {
    "columns": SchemaColumn[];
    "rowsScanned": number;

    /**
     * stopped at the row cap
     */
    "truncated": boolean;

    /** Creates a new SchemaResult instance. */
    constructor($$source: Partial<SchemaResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rowsScanned" in $$source)) {
            this["rowsScanned"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        return new SchemaResult($$parsedSource as Partial<SchemaResult>);
    }
}

// Private type creation functions
const $$createType0 = DumpTable.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = SchemaColumn.createFrom;
const $$createType4 = $Create.Array($$createType3);
