// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info is safe, non-secret build metadata exposed to diagnostics and the UI.
 */
export class Info {
    "productName": string;
    "version": string;
    "commit": string;
    "buildDate": string;
    "channel": string;
    "dirty": boolean;
    "goVersion": string;
    "wailsVersion": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("productName" in $$source)) {
            this["productName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("buildDate" in $$source)) {
            this["buildDate"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("goVersion" in $$source)) {
            this["goVersion"] = "";
        }
        if (!("wailsVersion" in $$source)) {
            this["wailsVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}
