// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Job is one tracked background task. Log is omitted from list views and filled
 * only by GetJob.
 */
export class Job {
    "id": string;

    /**
     * agent | dump | csv | …
     */
    "kind": string;

    /**
     * short human label
     */
    "title": string;
    "status": Status;

    /**
     * unix ms
     */
    "startedAt": number;

    /**
     * unix ms, 0 while running
     */
    "endedAt": number;
    "error": string;
    "log": string[];

    /** Creates a new Job instance. */
    constructor($$source: Partial<Job> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     */
    static createFrom($$source: any = {}): Job {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField7_0($$parsedSource["log"]);
        }
        return new Job($$parsedSource as Partial<Job>);
    }
}

/**
 * Status is a job's lifecycle state.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusRunning = "running",
    StatusSuccess = "success",
    StatusFailed = "failed",
    StatusCanceled = "canceled",
    StatusTimeout = "timeout",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
