// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails jobs ledger.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../context/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Append adds a log line to a job (no-op for an unknown id).
 */
export function Append(id: string, line: string): $CancellablePromise<void> {
    return $Call.ByID(2019055312, id, line);
}

/**
 * CancelJob requests cancellation of a running job via its registered hook.
 */
export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(3129460213, id);
}

/**
 * ClearFinished drops every non-running job from the ledger.
 */
export function ClearFinished(): $CancellablePromise<void> {
    return $Call.ByID(4065931283);
}

/**
 * Finish marks a running job terminal. It is idempotent — a later Finish (e.g. a
 * timeout racing a cancel) is ignored once the job has ended.
 */
export function Finish(id: string, status: $models.Status, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(1791160599, id, status, errMsg);
}

/**
 * GetJob returns one job including its log.
 */
export function GetJob(id: string): $CancellablePromise<$models.Job> {
    return $Call.ByID(1414725335, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListJobs returns all retained jobs (newest first) without their logs.
 */
export function ListJobs(): $CancellablePromise<$models.Job[]> {
    return $Call.ByID(1059784272).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Start registers a new running job and returns its id. cancel may be nil for a
 * job that can't be interrupted.
 */
export function Start(kind: string, title: string, cancel: context$0.CancelFunc): $CancellablePromise<string> {
    return $Call.ByID(1651399828, kind, title, cancel);
}

// Private type creation functions
const $$createType0 = $models.Job.createFrom;
const $$createType1 = $Create.Array($$createType0);
