// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails jobs ledger. Its exported methods are the complete
 * renderer contract. Producer operations deliberately remain package-level
 * functions so Wails cannot publish them as methods on this bound type.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob requests cancellation of an active job via its registered hook.
 */
export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(3129460213, id);
}

/**
 * ClearFinished drops every terminal job from the ledger.
 */
export function ClearFinished(): $CancellablePromise<void> {
    return $Call.ByID(4065931283);
}

/**
 * GetJob returns one job including its log.
 */
export function GetJob(id: string): $CancellablePromise<$models.Job> {
    return $Call.ByID(1414725335, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListJobs returns all retained jobs (newest first) without their logs.
 */
export function ListJobs(): $CancellablePromise<$models.Job[]> {
    return $Call.ByID(1059784272).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Job.createFrom;
const $$createType1 = $Create.Array($$createType0);
