// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Message is one conversation turn from the UI.
 */
export class Message {
    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * SendRequest is a chat request from the UI.
 */
export class SendRequest {
    "messages": Message[];

    /**
     * optional workspace context text
     */
    "context": string;

    /**
     * optional system-prompt override
     */
    "system": string;

    /** Creates a new SendRequest instance. */
    constructor($$source: Partial<SendRequest> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("system" in $$source)) {
            this["system"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SendRequest {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new SendRequest($$parsedSource as Partial<SendRequest>);
    }
}

// Private type creation functions
const $$createType0 = Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
