// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Artifact is one registered output. Stale/Missing are computed on read and not
 * authoritative when persisted.
 */
export class Artifact {
    "id": string;

    /**
     * report | chart | sql | dataset | answer | comparison | notebook | file
     */
    "kind": string;
    "title": string;

    /**
     * workspace-relative content file
     */
    "path": string;

    /**
     * what produced it (agent tool / feature)
     */
    "tool": string;
    "note": string;

    /**
     * workspace-relative inputs it derived from (lineage)
     */
    "sources": string[];
    "createdAt": number;
    "updatedAt": number;
    "archived": boolean;

    /**
     * a source is newer than the artifact (recomputed on read)
     */
    "stale": boolean;

    /**
     * the content file no longer exists (recomputed on read)
     */
    "missing": boolean;

    /** Creates a new Artifact instance. */
    constructor($$source: Partial<Artifact> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("archived" in $$source)) {
            this["archived"] = false;
        }
        if (!("stale" in $$source)) {
            this["stale"] = false;
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     */
    static createFrom($$source: any = {}): Artifact {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField6_0($$parsedSource["sources"]);
        }
        return new Artifact($$parsedSource as Partial<Artifact>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
