// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails artifacts registry.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateArtifact registers an existing workspace file as an artifact. If an
 * active artifact already points at the same path it is updated in place rather
 * than duplicated (so re-running a producer refreshes lineage/timestamp).
 */
export function CreateArtifact(a: $models.Artifact): $CancellablePromise<$models.Artifact> {
    return $Call.ByID(2492040169, a).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteArtifact removes the registry entry. The content file is intentionally
 * left on disk — deleting user files is the file tree's job, not this registry's.
 */
export function DeleteArtifact(id: string): $CancellablePromise<void> {
    return $Call.ByID(1741866102, id);
}

/**
 * GetArtifact returns one artifact by id.
 */
export function GetArtifact(id: string): $CancellablePromise<$models.Artifact> {
    return $Call.ByID(4054313471, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListArtifacts returns all registered artifacts (newest first) with freshness
 * computed.
 */
export function ListArtifacts(): $CancellablePromise<$models.Artifact[]> {
    return $Call.ByID(1191712718).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetArchived archives or restores an artifact (its content file is untouched).
 */
export function SetArchived(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(3670329107, id, archived);
}

// Private type creation functions
const $$createType0 = $models.Artifact.createFrom;
const $$createType1 = $Create.Array($$createType0);
