// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Column describes one column of a table.
 */
export class Column {
    "name": string;
    "type": string;
    "nullable": boolean;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * Profile is a saved connection. Password is input-only (json omitempty) and is
 * never persisted or returned — it is moved into the secret store on save.
 */
export class Profile {
    "id": string;
    "name": string;

    /**
     * sqlite | postgres | mysql
     */
    "kind": string;

    /**
     * sqlite
     */
    "file": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;

    /**
     * transport mode for postgres + mysql; empty = secure-by-default (see resolveTLS)
     */
    "sslMode": string;
    "secretRef": string;

    /**
     * input only — never persisted
     */
    "password"?: string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("secretRef" in $$source)) {
            this["secretRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

/**
 * QueryResult is a read-only query's columns + stringified rows. Nulls is a mask
 * parallel to Rows marking which cells were SQL NULL, so the UI can distinguish a
 * real NULL from the literal text "NULL" out-of-band (not by string compare).
 */
export class QueryResult {
    "columns": string[];
    "rows": string[][];
    "nulls": boolean[][];
    "rowCount": number;
    "truncated": boolean;
    "elapsedMs": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("nulls" in $$source)) {
            this["nulls"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("nulls" in $$parsedSource) {
            $$parsedSource["nulls"] = $$createField2_0($$parsedSource["nulls"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * Table is a schema object listed for a connection.
 */
export class Table {
    "name": string;
    "type": string;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Table($$parsedSource as Partial<Table>);
    }
}

/**
 * TestResult reports a connectivity check.
 */
export class TestResult {
    "ok": boolean;
    "message": string;

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
