// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails db service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteProfile removes a profile and its stored credential.
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3790458378, id);
}

/**
 * ListColumns returns the columns of a table for the schema browser. The query
 * is service-issued (not user SQL); sqlite identifiers are validated, network
 * engines use bound parameters.
 */
export function ListColumns(id: string, table: string): $CancellablePromise<$models.Column[]> {
    return $Call.ByID(294926913, id, table).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListProfiles returns saved profiles (never the password).
 */
export function ListProfiles(): $CancellablePromise<$models.Profile[]> {
    return $Call.ByID(372126764).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTables returns base tables and views for the connection.
 */
export function ListTables(id: string): $CancellablePromise<$models.Table[]> {
    return $Call.ByID(1247256711, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadError returns a user-facing message if the saved profiles file was corrupt
 * on load (and was backed up), or "" otherwise. Bound to the UI so the silent
 * "my connections disappeared" case becomes visible.
 */
export function LoadError(): $CancellablePromise<string> {
    return $Call.ByID(3544410456);
}

/**
 * Query runs a guarded, read-only SELECT and returns columns + rows.
 */
export function Query(id: string, query: string, limit: number): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(1437416626, id, query, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SaveProfile creates or updates a profile. A non-empty Password is stored
 * (encrypted) in the secret store and cleared from the persisted profile.
 */
export function SaveProfile(p: $models.Profile): $CancellablePromise<$models.Profile> {
    return $Call.ByID(2324040180, p).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TestProfile opens the connection and pings it.
 */
export function TestProfile(id: string): $CancellablePromise<$models.TestResult> {
    return $Call.ByID(2774820891, id).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Column.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Profile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Table.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.QueryResult.createFrom;
const $$createType7 = $models.TestResult.createFrom;
