// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Editor holds editor-pane preferences mirrored into Monaco on the frontend.
 */
export class Editor {
    "fontSize": number;
    "tabSize": number;
    "wordWrap": boolean;
    "minimap": boolean;

    /**
     * monaco theme id
     */
    "theme": string;
    "formatOnSave": boolean;

    /** Creates a new Editor instance. */
    constructor($$source: Partial<Editor> = {}) {
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("tabSize" in $$source)) {
            this["tabSize"] = 0;
        }
        if (!("wordWrap" in $$source)) {
            this["wordWrap"] = false;
        }
        if (!("minimap" in $$source)) {
            this["minimap"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("formatOnSave" in $$source)) {
            this["formatOnSave"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Editor instance from a string or object.
     */
    static createFrom($$source: any = {}): Editor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Editor($$parsedSource as Partial<Editor>);
    }
}

/**
 * LLM holds non-secret provider configuration. The API key itself is NEVER
 * stored here — only a reference (APIKeyRef) into the dedicated secret store.
 */
export class LLM {
    /**
     * "ollama" | "openai" | "custom"
     */
    "provider": string;
    "baseURL": string;
    "model": string;
    "apiKeyRef": string;

    /**
     * RequestTimeoutSec bounds a single LLM request (one agent completion, or
     * the whole Ask-mode stream). User-tunable because local-model latency
     * varies wildly with hardware. 0 means "use the default" — see RequestTimeout.
     */
    "requestTimeoutSec": number;

    /** Creates a new LLM instance. */
    constructor($$source: Partial<LLM> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKeyRef" in $$source)) {
            this["apiKeyRef"] = "";
        }
        if (!("requestTimeoutSec" in $$source)) {
            this["requestTimeoutSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLM instance from a string or object.
     */
    static createFrom($$source: any = {}): LLM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLM($$parsedSource as Partial<LLM>);
    }
}

/**
 * Settings is the full persisted preference set.
 */
export class Settings {
    /**
     * app theme: "dark" | "light"
     */
    "theme": string;
    "lastWorkspace": string;
    "recentWorkspaces": string[];

    /**
     * base font size for the app chrome (px)
     */
    "uiFontSize": number;
    "editor": Editor;
    "llm": LLM;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("lastWorkspace" in $$source)) {
            this["lastWorkspace"] = "";
        }
        if (!("recentWorkspaces" in $$source)) {
            this["recentWorkspaces"] = [];
        }
        if (!("uiFontSize" in $$source)) {
            this["uiFontSize"] = 0;
        }
        if (!("editor" in $$source)) {
            this["editor"] = (new Editor());
        }
        if (!("llm" in $$source)) {
            this["llm"] = (new LLM());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentWorkspaces" in $$parsedSource) {
            $$parsedSource["recentWorkspaces"] = $$createField2_0($$parsedSource["recentWorkspaces"]);
        }
        if ("editor" in $$parsedSource) {
            $$parsedSource["editor"] = $$createField4_0($$parsedSource["editor"]);
        }
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField5_0($$parsedSource["llm"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Editor.createFrom;
const $$createType2 = LLM.createFrom;
