// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound Wails service for settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Load returns the persisted settings, falling back to defaults for any missing
 * fields or if no file exists yet.
 */
export function Load(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2509701163).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RememberWorkspace records path as the last-opened workspace and pushes it to
 * the front of the recents list, returning the updated settings.
 */
export function RememberWorkspace(path: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2975979585, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Save persists the full settings object atomically.
 */
export function Save($in: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2754879942, $in);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
