// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColumnProfile {
    "name": string;
    "sqlType": string;
    "nonNull": number;
    "null": number;
    "distinct": number;
    "distinctCapped": boolean;
    "min": string;
    "max": string;
    "top": ValueCount[];

    /** Creates a new ColumnProfile instance. */
    constructor($$source: Partial<ColumnProfile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sqlType" in $$source)) {
            this["sqlType"] = "";
        }
        if (!("nonNull" in $$source)) {
            this["nonNull"] = 0;
        }
        if (!("null" in $$source)) {
            this["null"] = 0;
        }
        if (!("distinct" in $$source)) {
            this["distinct"] = 0;
        }
        if (!("distinctCapped" in $$source)) {
            this["distinctCapped"] = false;
        }
        if (!("min" in $$source)) {
            this["min"] = "";
        }
        if (!("max" in $$source)) {
            this["max"] = "";
        }
        if (!("top" in $$source)) {
            this["top"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnProfile {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top" in $$parsedSource) {
            $$parsedSource["top"] = $$createField8_0($$parsedSource["top"]);
        }
        return new ColumnProfile($$parsedSource as Partial<ColumnProfile>);
    }
}

export class ValueCount {
    "value": string;
    "count": number;

    /** Creates a new ValueCount instance. */
    constructor($$source: Partial<ValueCount> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValueCount instance from a string or object.
     */
    static createFrom($$source: any = {}): ValueCount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValueCount($$parsedSource as Partial<ValueCount>);
    }
}

// Private type creation functions
const $$createType0 = ValueCount.createFrom;
const $$createType1 = $Create.Array($$createType0);
